### ISSUE TITLE
Support for ":memory:" DB

### ISSUE THREAD

**Issue by nikgraf** [OP-Engineering/op-sqlite#1]
SQlite support an in memory version of the DB where data is not persisted https://www.sqlite.org/inmemorydb.html

This is useful for using Sqlite as a sync state management solution where data is not supposed to be persisted. E.g. Johannes is working livestore and the new version is using Sqlite in memory for fast reactive queries and a second connection to to persist the data - here an older video of the concept https://www.youtube.com/watch?v=qHSI5rxTp_Q

Due this always concatinating https://github.com/OP-Engineering/op-sqlite/blob/fbd30039446ae92f028dd4cca2951e07af5e58ce/cpp/bridge.cpp#L76

https://github.com/OP-Engineering/op-sqlite/blob/fbd30039446ae92f028dd4cca2951e07af5e58ce/cpp/bridge.cpp#L68-L72

it is not possible to use `op-sqlite` with in memory mode.

Btw would also be interesting to have benchmarks in comparison how much faster this is.

**Comment by ospfranco** [comment]
Interesting. Well, seems easy enough to do with an extra param. Feel free to submit a PR.

**Comment by ospfranco** [comment]
I wanted to see if this would improve performance and it doesn't seem that way, at least on reads, maybe writes are faster but I'm not measuring those atm.

![Screenshot 2023-11-09 at 14 35 42](https://github.com/OP-Engineering/op-sqlite/assets/1634213/9bbe70b5-a27c-41f2-94b0-8eb5b4e8773e)

In any case, support has been added in version `1.0.4`.

**Comment by nikgraf** [comment]
awesome, thanks a lot :)
