### ISSUE TITLE
Can't use existing db

### ISSUE THREAD

**Issue by Gul7333** [OP-Engineering/op-sqlite#100]
I have a db which contain data... I am using this db in my app... But I have hard time understanding your doc how to use existing db... How can I use existing db placed in asset folder ( data.db)

**Comment by ospfranco** [comment]
You can't. The assets are on the app bundle, on iOS you can access but are overwritten on each app install, on Android the app bundle is zipped so you can't connect to it.

You have to move the database to the file system, the docs are quite clear on how to do it.

https://ospfranco.notion.site/Configuration-6b8b9564afcc4ac6b6b377fe34475090
