### ISSUE TITLE
The 'Pods-DevKin' target has frameworks with conflicting names: crsqlite.xcframework.

### ISSUE THREAD

**Issue by Volland** [OP-Engineering/op-sqlite#101]
**Describe the bug**
I get error on updating a library 
!] The 'Pods-DevKin' target has frameworks with conflicting names: crsqlite.xcframework.
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: The 'Pods-DevKin' target has frameworks with conflicting names: crsqlite.xcframework.

**Versions:**

- OS and version: iOS 17
- op-sqlite version: 6.0.1
- RN version:  0.73.0
- New Architecture: yes 

**Reproducible example**
Create a minimal reproduction example, otherwise I won't take a look. I'm serious, no example = no solution.

**Comment by ospfranco** [comment]
no idea, sorry! try clearing the caches and re-installing the pods from scratch. Maybe a dependency really has the same crsqlite.xcframework
