### ISSUE TITLE
Android openRemote fails with libsql://xxxx.turso.io: TLS error: no valid native root CA certificates found (0 invalid)]

### ISSUE THREAD

**Issue by abdelhameedhamdy** [OP-Engineering/op-sqlite#102]
When calling openRemote function, the following error appears:

![CleanShot 2024-06-01 at 09 23 36@2x](https://github.com/OP-Engineering/op-sqlite/assets/1634213/d87b5b6f-d8a8-4774-8d7c-07c0a23b51b1)

**Versions:**
- OS and version: Android 12 device and emulator
- op-sqlite version: 6.0.2-beta4
- RN version: 0.74.1
- New Architecture: Yes
- EXPO framework v51.0.8

**Reproducible example**
A demo Turso db created using [turso cli](https://docs.turso.tech/cli/introduction)
 
```js
  const remoteDb = openRemote({
    url: process.env.EXPO_PUBLIC_TURSO_DATABASE_URL ?? "",
    authToken: process.env.EXPO_PUBLIC_TURSO_AUTH_TOKEN ?? "",
  });
  const result = remoteDb.execute("SELECT * FROM users");
```

**Comment by abdelhameedhamdy** [comment]
One more error irrelevant to this one, I have .so file extension was working properly with v6.0.1, when upgraded to v6.0.2-beta4, is not loading and gives Error: Exception in HostFunction: <unknown> when trying to call `db.loadExtension(...)`.

**Comment by ospfranco** [comment]
hmm how can I setup a remote database to test this?

As for loading extensions, they are not supported by libsql.

**Comment by ospfranco** [comment]
<img src="https://github.com/OP-Engineering/op-sqlite/assets/1634213/aceaf394-4914-4e91-b585-4789255c6a38" width="300"/>

You might be doing something wrong, here is a connection to a turso remote db. I don't know why you are not getting descriptive native errors either. You should get a "loading extensions is not supported by libsql" error too.

**Comment by abdelhameedhamdy** [comment]
I have disabled libsql in package.json, and it shows the same error Exception in HostFunction. I am not sure what is wrong with the setup just installed the op-sqlite package in expo project and run it for android platform, db created properly, but got this error with libsql and loadExtension with libsql: false.

**Comment by ospfranco** [comment]
You must be doing something wrong. The example app is working just fine.

**Comment by abdelhameedhamdy** [comment]
I got a descriptive error, Error opening URL libsql://xxxx.turso.io: TLS error: no valid native root CA certificates found (0 invalid)], in openRemote function.

with a new expo project and op-sql release 6.0.4 installed.

**Comment by ospfranco** [comment]
Looks like this is a turso/libsql error, nothing to do with this library I suppose. Maybe enabling unsecure http communication or trying to connect from desktop to make sure the url you are using is correct is a good way to test what you are doing wrong. However I already showed i can connect to turso without issues. You have to debug this yourself.

**Comment by abdelhameedhamdy** [comment]
The url db is tested from terminal using curl, it query data with no issue.

**Comment by abdelhameedhamdy** [comment]
Ok, I got it, your testing is on iOS,  rebuilt and tested vs iOS and it works with no issue.

So, this error belongs to Android platform.

**Comment by ospfranco** [comment]
Aha! The rust code is probably missing openSSL. I will take a look.

**Comment by ospfranco** [comment]
Turns out the issue is on the http library used by libsql itself. There needs to be some changes on libsql in order to use web certificates instead of OS installed CA certificates. Once they make a new API to open a remote connection available I will patch it. For now nothing I can do.
