### ISSUE TITLE
[question] any plans on supporting sqlite_config?

### ISSUE THREAD

**Issue by iliapnmrv** [OP-Engineering/op-sqlite#107]
Hey! Thank you for this library!

Do you have any plans on supporting [sqlite_config](https://sqlite.org/c3ref/c_config_covering_index_scan.html) feature? I would like to implement db logging using [SQLITE_CONFIG_LOG](https://www.sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfiglog).

Maybe you have any suggestions on how to implement it using current version of op-sqlite or I might try doing it myself

**Comment by ospfranco** [comment]
From a quick read it looks like it needs a C function pointer, which you won't be able to do from JS code anyways. I would have to create a lot of infra code including a hardcoded C function so it can be bound to a dynamically registered JS function.

It's the same I had to do for the update hook. It's a lot of work and a lot of code to maintain in the future so I will probably not do this unless there is $$$ involved in creating and maintaining the feature.

If you really want this, your best bet is to patch the source code via patch-package and implement the C function on `bridge.cpp`

**Comment by iliapnmrv** [comment]
got it, thank you for quick response!
