### ISSUE TITLE
reactiveExecute is not firing after re-subscription

### ISSUE THREAD

**Issue by maksym-kyryliuk** [OP-Engineering/op-sqlite#108]
Hello!

I'm trying to use the recently introduced reactiveExecute functionality and found an issue on Android 12.

With the code below the subscription works correctly on the screen, but only the first time. 
If I go back from the screen the return method of the useEffect and unsubscription are applied.
Any further screen openings are never fire the reactiveExecute again until the app is fully closed and reopened,

```javascript
  React.useEffect(() => {
    const unsubscribe = db.reactiveExecute({
      query: "SELECT * FROM categories",
      arguments: [],
      fireOn: [
        {
          table: "categories"
        }
      ],
      callback: response => {
        console.log(response.rows._array);
      }
    });

    return () => {
      unsubscribe();
    };
  }, []);
``` 

Navigation between screens is made by github.com/react-navigation/react-navigation

SQLite config:

```
  "op-sqlite": {
    "sqlcipher": false,
    "crsqlite": false,
    "performanceMode": "0",
    "sqliteFlags": "-DSQLITE_DQS=0",
    "libsql": false,
    "iosSqlite": false,
    "fts5": true
  }
```

Tested on Android emulator and real device

**Versions:**
- OS and version: Android 12 (emulator), Android 13
- op-sqlite version: 6.0.6
- RN version: 0.73.4
- New Architecture: Yes

**Comment by ospfranco** [comment]
Not sure I understand what you mean... if you go back then the unsubscribe is called, what's wrong incorrect about that? Nothing should be fired once unsubscribe is called.

**Comment by ospfranco** [comment]
Create a reproducible example, please.

**Comment by maksym-kyryliuk** [comment]
@ospfranco here is the [link to the repository](https://github.com/maksym-kyryliuk/opsqliteIssue)

I am also attaching the video with a flow:

https://github.com/OP-Engineering/op-sqlite/assets/15281327/46d8b5a8-13a0-4bd9-8f43-348d9abf86a5

**Comment by ospfranco** [comment]
Found the issue, will release it after CI passes. Thanks for testing!

**Comment by maksym-kyryliuk** [comment]
@ospfranco found another case related to reactiveExecute itself, but not a re-subscription. 

when I try to subscribe to a single row or even cell and **pass parameters in the "arguments" section**, I can't get data from the response object in the callback function.

example:

`React.useEffect(() => {
    const unsubscribe = db.reactiveExecute({
      query: 'SELECT title FROM categories where id = ?',
      arguments: [route.params.category.id],
      fireOn: [
        {
          table: 'categories',
        },
      ],
      callback: response => {
        console.log(response);
      },
    });

    return () => {
      unsubscribe();
    };
  }, []);`
  
  the log looks like this:
  
`  `{"insertId": 1, "metadata": [{"index": 0, "name": "title", "type": "TEXT"}], "rowsAffected": 1}`

There is no .rows object in the response and as a result, I can't read the updated data neither using `response.rows?._array` nor  `response.rows.item(0)`.

Although "SELECT title FROM categories" and empty arguments array works fine.

I've tried different ways, including adding [rowid] in the fireOn (I know that id and rowid are differing things), but nothing works when I specify '?' in the query and pass parameters.

Maybe I'm doing something wrong?

The reproducable example [is under the same link](https://github.com/maksym-kyryliuk/opsqliteIssue)
