### ISSUE TITLE
Can we use it with typeorm I don't see any

### ISSUE THREAD

**Issue by wogno** [OP-Engineering/op-sqlite#112]
<img width="366" alt="Capture d’écran 2024-06-27 à 12 03 47" src="https://github.com/OP-Engineering/op-sqlite/assets/31076843/1804c4f0-34f5-4d2e-b72d-ce3d20351c34">

What should I put in adaptor, don't see any information

**Comment by ospfranco** [comment]
Duplicated of #6

**Comment by wogno** [comment]
Ok, thank, but how to implement driver I don't see any resource on web

**Comment by wogno** [comment]
I tested this one, but not working on last version,  OPSQLiteConnection is not found
`import type {
    OPSQLiteConnection,
    QueryResult,
    Transaction,
  } from '@op-engineering/op-sqlite';
  import {open} from '@op-engineering/op-sqlite';
  
  const enhanceQueryResult = (result: QueryResult): void => {
    if (result.rows == null) {
      result.rows = {
        _array: [],
        item: (index: number) => result.rows?._array[index],
        length: 0,
      };
    } else {
      result.rows.item = (index: number) => result.rows?._array[index];
    }
  };
  
  export const typeORMDriver = {
    openDatabase: (
      options: {
        location?: string;
        name: string;
      },
      ok: (database: OPSQLiteConnection) => void,
      fail: (message: string) => void,
    ) => {
      try {
        const database = open({location: options.location, name: options.name});
  
        const connection = {
          attach: (
            databaseNameToAttach: string,
            alias: string,
            location: string | undefined,
            callback: () => void,
          ) => {
            database.attach(databaseNameToAttach, alias, location);
  
            callback();
          },
          close: (ok: () => void, fail: (argument0: unknown) => void) => {
            try {
              database.close();
              ok();
            } catch (error) {
              fail(error);
            }
          },
          detach: (alias: string, callback: () => void) => {
            database.detach(alias);
  
            callback();
          },
          executeSql: async (
            sql: string,
            parameters: unknown[] | undefined,
            ok: (response: QueryResult) => void,
            fail: (message: string) => void,
          ) => {
            try {
              const response = await database.executeAsync(sql, parameters);
  
              enhanceQueryResult(response);
              ok(response);
            } catch (error) {
              fail(error as unknown as string);
            }
          },
          transaction: (
            function_: (tx: Transaction) => Promise<void>,
          ): Promise<void> => database.transaction(function_),
        };
  
        ok(connection as unknown as OPSQLiteConnection);
  
        return connection;
      } catch (error) {
        fail(error as unknown as string);
      }
    },
  };
  `

**Comment by ospfranco** [comment]
That was the old driver mate. You will have to adjust it for the latest version.

**Comment by wogno** [comment]
Please, have you have a model or ressource since 3 days that I do my best without any progress. Read ressources and many ressource, but nothing working. 

I I can I have a model that will be really helpfull for me.

**Comment by wogno** [comment]
`
import * as QuickSQLite from '@op-engineering/op-sqlite'
// import {QueryResult} from '@op-engineering/op-sqlite'

// Enhance some host functions

// Add 'item' function to result object to allow the sqlite-storage typeorm driver to work
const enhanceQueryResult = (result: QuickSQLite.QueryResult): void => {
  // Add 'item' function to result object to allow the sqlite-storage typeorm driver to work
  if (result.rows == null) {
    result.rows = {
      _array: [],
      length: 0,
      item: (idx: number) => result.rows._array[idx],
    };
  } else {
    result.rows.item = (idx: number) => result.rows._array[idx];
  }
};

//   _________     _______  ______ ____  _____  __  __            _____ _____
//  |__   __\ \   / /  __ \|  ____/ __ \|  __ \|  \/  |     /\   |  __ \_   _|
//     | |   \ \_/ /| |__) | |__ | |  | | |__) | \  / |    /  \  | |__) || |
//     | |    \   / |  ___/|  __|| |  | |  _  /| |\/| |   / /\ \ |  ___/ | |
//     | |     | |  | |    | |___| |__| | | \ \| |  | |  / ____ \| |    _| |_
//     |_|     |_|  |_|    |______\____/|_|  \_\_|  |_| /_/    \_\_|   |_____|

/**
 * DO NOT USE THIS! THIS IS MEANT FOR TYPEORM
 * If you are looking for a convenience wrapper use `connect`
 */
export const typeORMDriver = {
  openDatabase: (
    options: {
      name: string;
      location?: string;
    },
    ok: (db: any) => void,
    fail: (msg: string) => void
  ): any => {
    try {
      const database = QuickSQLite.open({location: options.location, name: options.name});

      const connection = {
        executeSql: async (
          sql: string,
          params: any[] | undefined,
          ok: (res: QueryResult) => void,
          fail: (msg: string) => void
        ) => {
          try {
            let response = await database.executeAsync(
              sql,
              params
            );
            enhanceQueryResult(response);
            ok(response);
          } catch (e) {
            fail(e);
          }
        },
        transaction: (
          fn: (tx: QuickSQLite.Transaction) => Promise<void>
        ): Promise<void> => {
          return database.transaction(fn);
        },
        close: (ok: any, fail: any) => {
          try {
            database.close();
            ok();
          } catch (e) {
            fail(e);
          }
        },
        attach: (
          dbNameToAttach: string,
          alias: string,
          location: string | undefined,
          callback: () => void
        ) => {
          database.attach(options.name, dbNameToAttach, alias, location);

          callback();
        },
        detach: (alias, callback: () => void) => {
          database.detach(options.name, alias);

          callback();
        },
      };

      ok(connection);

      return connection;
    } catch (e) {
      fail(e);
    }
  },
};`

**Comment by wogno** [comment]
I new one base on quick-sqlite typeorm but still the same error, but work well when I use the last package. It will be really cool, if we have adaptor joined, or a files listed them. 

When I use the new one I get this error on native part, and I app crash, during initalization of db

<img width="570" alt="Capture d’écran 2024-06-27 à 12 53 12" src="https://github.com/OP-Engineering/op-sqlite/assets/31076843/0794288f-4fb0-45c4-8249-1e5e1c98426b">

`
import * as QuickSQLite from '@op-engineering/op-sqlite'
// import {QueryResult} from '@op-engineering/op-sqlite'

// Enhance some host functions

// Add 'item' function to result object to allow the sqlite-storage typeorm driver to work
const enhanceQueryResult = (result: QuickSQLite.QueryResult): void => {
  // Add 'item' function to result object to allow the sqlite-storage typeorm driver to work
  if (result.rows == null) {
    result.rows = {
      _array: [],
      length: 0,
      item: (idx: number) => result.rows._array[idx],
    };
  } else {
    result.rows.item = (idx: number) => result.rows._array[idx];
  }
};

//   _________     _______  ______ ____  _____  __  __            _____ _____
//  |__   __\ \   / /  __ \|  ____/ __ \|  __ \|  \/  |     /\   |  __ \_   _|
//     | |   \ \_/ /| |__) | |__ | |  | | |__) | \  / |    /  \  | |__) || |
//     | |    \   / |  ___/|  __|| |  | |  _  /| |\/| |   / /\ \ |  ___/ | |
//     | |     | |  | |    | |___| |__| | | \ \| |  | |  / ____ \| |    _| |_
//     |_|     |_|  |_|    |______\____/|_|  \_\_|  |_| /_/    \_\_|   |_____|

/**
 * DO NOT USE THIS! THIS IS MEANT FOR TYPEORM
 */
export const typeORMDriver = {
  openDatabase: (
    options: {
      name: string;
      location?: string;
    },
    ok: (db: any) => void,
    fail: (msg: string) => void
  ): any => {
    try {
      const database = QuickSQLite.open({location: options.location, name: options.name});

      const connection = {
        executeSql: async (
          sql: string,
          params: any[] | undefined,
          ok: (res: QueryResult) => void,
          fail: (msg: string) => void
        ) => {
          try {
            let response = await database.executeAsync(
              sql,
              params
            );
            enhanceQueryResult(response);
            ok(response);
          } catch (e) {
            fail(e);
          }
        },
        transaction: (
          fn: (tx: QuickSQLite.Transaction) => Promise<void>
        ): Promise<void> => {
          return database.transaction(fn);
        },
        close: (ok: any, fail: any) => {
          try {
            database.close();
            ok();
          } catch (e) {
            fail(e);
          }
        },
        attach: (
          dbNameToAttach: string,
          alias: string,
          location: string | undefined,
          callback: () => void
        ) => {
          database.attach(options.name, dbNameToAttach, alias, location);

          callback();
        },
        detach: (alias, callback: () => void) => {
          database.detach(options.name, alias);

          callback();
        },
      };

      ok(connection);

      return connection;
    } catch (e) {
      fail(e);
    }
  },
};`

**Comment by ospfranco** [comment]
As mentioned on the closed ticket, I will not do this myself. TypeORM was a pain to maintain. You should go ask StackOverflow.

**Comment by blumk** [comment]
@wogno Here's a TypeORM driver compatible with `op-sqlite@7.1.0`:

```
// inspired by https://github.com/lukaszkurantdev/blog-sqlite-comparison/blob/main/opsqlite/src/typeORMDriver.ts
import { QueryResult, Transaction, open } from '@op-engineering/op-sqlite';

const enhanceQueryResult = (result: QueryResult): void => {
  if (result.rows == null) {
    result.rows = {
      _array: [],
      length: 0,
      item: (idx: number) => result.rows?._array[idx],
    };
  } else {
    result.rows.item = (idx: number) => result.rows?._array[idx];
  }
};

export const typeORMDriver = {
  openDatabase: (
    options: {
      name: string;
      location?: string;
      encryptionKey: string;
    },
    ok: (db: any) => void,
    fail: (msg: string) => void,
  ): any => {
    try {
      if (!options.encryptionKey || options.encryptionKey.length === 0) {
        throw new Error('[op-sqlite]: Encryption key is required');
      }

      const database = open({
        location: options.location,
        name: options.name,
        encryptionKey: options.encryptionKey,
      });

      const connection = {
        executeSql: async (
          sql: string,
          params: any[] | undefined,
          ok: (res: QueryResult) => void,
          fail: (msg: string) => void,
        ) => {
          try {
            const response = await database.executeAsync(sql, params);
            enhanceQueryResult(response);
            ok(response);
          } catch (e) {
            fail(`[op-sqlite]: Error executing SQL: ${e as string}`);
          }
        },
        transaction: (fn: (tx: Transaction) => Promise<void>): Promise<void> => {
          return database.transaction(fn);
        },
        close: (ok: any, fail: any) => {
          try {
            database.close();
            ok();
          } catch (e) {
            fail(`[op-sqlite]: Error closing db: ${e as string}`);
          }
        },
        attach: (
          dbNameToAttach: string,
          alias: string,
          location: string | undefined,
          callback: () => void,
        ) => {
          database.attach(options.name, dbNameToAttach, alias, location);

          callback();
        },
        detach: (alias: string, callback: () => void) => {
          database.detach(options.name, alias);

          callback();
        },
      };

      ok(connection);

      return connection;
    } catch (e) {
      fail(`[op-sqlite]: Error opening database: ${e as string}`);
    }
  },
};

```

**Comment by wogno** [comment]
@blumk really thanks for this help.
