### ISSUE TITLE
reactiveExecute - Can't get data in callback when passing parameters in the arguments property

### ISSUE THREAD

**Issue by maksym-kyryliuk** [OP-Engineering/op-sqlite#118]
Hey @ospfranco 

To continue #108 I found another case related to reactiveExecute, but not a re-subscription. 

when I try to subscribe to a single row or even cell and **pass parameters in the "arguments" section**, I can't get data from the response object in the callback function.

example:

```javascript
React.useEffect(() => {
    const unsubscribe = db.reactiveExecute({
      query: 'SELECT title FROM categories where id = ?',
      arguments: [route.params.category.id],
      fireOn: [
        {
          table: 'categories',
        },
      ],
      callback: response => {
        console.log(response);
      },
    });
    return () => {
      unsubscribe();
    };
  }, []);
``` 
  
 The log looks like this:
  
`{"insertId": 1, "metadata": [{"index": 0, "name": "title", "type": "TEXT"}], "rowsAffected": 1}`

There is no .rows object in the response and as a result, I can't read the updated data neither using `response.rows?._array` nor  `response.rows.item(0)`.

Although `"SELECT title FROM categories"` and **empty arguments array** works fine.

I've tried different ways, including adding **[rowid]** in the **fireOn** (I know that id and rowid are different things), but nothing works when I specify `'?'` in the query and pass some parameters.

Maybe I'm doing something wrong? 

The reproducible example [is under the same link](https://github.com/maksym-kyryliuk/opsqliteIssue)

Tested on Android emulator

**Versions:**
OS and version: Android 12 
op-sqlite version: 6.1.1
RN version: 0.73.4
New Architecture: Yes

**Comment by ospfranco** [comment]
Found the issue, forgot to change the name of the "arguments" prop, when I was designing the API, thanks for testing again!

**Comment by ospfranco** [comment]
New PR

https://github.com/OP-Engineering/op-sqlite/pull/119

Waiting for CI and then I will merge and release a new version.

**Comment by ospfranco** [comment]
Released in `6.1.2`

**Comment by maksym-kyryliuk** [comment]
@ospfranco I need some help with understanding another issue. I have a hook on the page:

```
  useEffect(() => {
    const unsubscribe = db.reactiveExecute({
      query: `SELECT
          a.id,
          a.title,
          COALESCE(SUM(
            CASE
              WHEN r.type= 2 THEN COALESCE(r.converted_sum, r.sum)
              ELSE -COALESCE(r.converted_sum, r.sum) 
            END
          ), 0) AS sum
        FROM accounts a
        LEFT JOIN records r ON a.id = r.account_id
        GROUP BY a.id
      `,
      arguments: [],
      fireOn: [
        {
          table: "accounts"
        }
      ],
      callback: response => {
        console.log("Accounts updated ", response);
      }
    });
    return () => {
      unsubscribe();
    };
  }, []);
```

after updating to 6.1.2 every time the reactiveExecute fires, I get the **response** object with an error:
`[Error: [op-sqlite] SQLite code: 11 execution error: database disk image is malformed]`

until I remove the `GROUP BY a.id`. Without it any SELECT/JOIN/WHERE works fine.

The DB file is OK, because the same query (with GROUP BY) as above runs on the screen opening without any issue and returns data.

What could be wrong with it?

**Comment by ospfranco** [comment]
Uff no idea buddy. I actually don't do that much SQL. You can try running the same prepared statement without the hook, just to debug it, but otherwise chatgpt says there is some sort of index corruption. I assume after modifying the table the indexes need to be recreated and the query reset somehow?

**Comment by maksym-kyryliuk** [comment]
@ospfranco I have a few more details on the faced issue. There is something wrong with the table's id (primary key). If I remove it from the reactiveExecute query, it works without issue.

Here is my use-case:

I have 3 tables - accounts, records, transactions:

`
       CREATE TABLE IF NOT EXISTS accounts (
            id           TEXT PRIMARY KEY NOT NULL,
            title        TEXT
        );      
        CREATE TABLE IF NOT EXISTS transactions (
            id          TEXT PRIMARY KEY NOT NULL,
        );
        
        CREATE TABLE IF NOT EXISTS tags (
            id         TEXT PRIMARY KEY NOT NULL,
            name       TEXT NOT NULL,
            user_id    TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES profiles(id)
        );
        
        CREATE TABLE IF NOT EXISTS records (
            id                    TEXT PRIMARY KEY NOT NULL,
            amount                REAL NOT NULL,
            currency              TEXT NOT NULL,
            converted_amount      REAL NULL,
            conversion_rate       REAL NULL,
            record_type           INTEGER NOT NULL,
            balance_type          INTEGER NOT NULL,
            date_at               TIMESTAMP NOT NULL,
            account_id            TEXT NOT NULL,
            transaction_id        TEXT NOT NULL,
            category_id           TEXT NULL,
            associated_account_id TEXT NULL,
            user_id               TEXT NOT NULL,
            created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES profiles(id),
            FOREIGN KEY(account_id) REFERENCES accounts(id),
            FOREIGN KEY(category_id) REFERENCES categories(id),
            FOREIGN KEY(transaction_id) REFERENCES transactions(id),
            FOREIGN KEY(associated_account_id) REFERENCES accounts(id)
        );

`

**Comment by maksym-kyryliuk** [comment]
@ospfranco I have a few more details on the faced issue. It seems that it might be something wrong with the table's id (primary key). If I remove it from the reactiveExecute query, it works correctly.

Here is my use-case:

I have 3 tables - accounts, records, transactions, Primary key is uuid.v4() here:

```
      CREATE TABLE IF NOT EXISTS accounts (
            id           TEXT PRIMARY KEY NOT NULL,
            title        TEXT
        );      

        CREATE TABLE IF NOT EXISTS transactions (
            id          TEXT PRIMARY KEY NOT NULL,
        );

        CREATE TABLE IF NOT EXISTS records (
            id                          TEXT PRIMARY KEY NOT NULL,
            sum                       REAL NOT NULL,
            converted_sum      REAL NULL,
            FOREIGN KEY(transaction_id) REFERENCES transactions(id),
            FOREIGN KEY(account_id) REFERENCES accounts(id)
        );

```

I have a screen with a list of accounts and the ability to delete them. The delete logic looks like this:

```
     const commands: SQLBatchTuple[] = [
        ["DELETE FROM records WHERE ...", [id]],
        ["DELETE FROM transactions WHERE ...", [id]],
        ["DELETE FROM accounts WHERE id = ?", [id]]
      ];
      await db.executeBatchAsync(commands);
```

I'm trying to delete a single 'account' and expect that reactiveExecute will return a collection without the deleted one.



I played with the SQL statement in the **reactiveExecute** and realized that if I specify the `id` in any way (in the SELECT, WHERE, or GROUP) the request returns an error `[Error: [op-sqlite] SQLite code: 11 execution error: database disk image is malformed]` for complex SQL like 
```
SELECT a.id, a.title,
  COALESCE(SUM(
    CASE
      WHEN r.type= 2 THEN COALESCE(r.converted_sum, r.sum)
      ELSE -COALESCE(r.converted_sum, r.sum) 
    END
  ), 0) AS sum
FROM accounts a
LEFT JOIN records r ON a.id = r.account_id
GROUP BY a.id
```

If I leave simplified SQL like `SELECT id from accounts` in the reactiveExecute, it has no errors, but the response contains all ids including the deleted one. Meanwhile, DELETE works correctly, it removes the rows from the db. 

In case if remove the `id` from it and leave something like this `SELECT * from accounts` or `SELECT title, order from accounts`, the reactiveExecute works perfectly.

I'm not good at DB internals, but it looks like a cache issue of the primary key or reactiveExecute grabs the state of db before execute/executeBatch ends. What do you think about it?

**Comment by ospfranco** [comment]
Like I said, try with a prepared statement alone. But this looks like sqlite quirk and not with the library

**Comment by ospfranco** [comment]
Sorry, I was not on the computer, but just re-read your last comment. The queries are executed based on the [`sqlite3_update_hook`](https://www.sqlite.org/c3ref/update_hook.html) which means it will not execute at the end of the `executeBatch` but after each sql statement that touches the table. So yeah, it will include intermediate results. It is either a internal quirk of sqlite where specifying a text id needs to rebuild the index or somehow the internal prepared statement needs to be resetted before executing after an index has changed. That's why I keep saying, try it with a pure `prepareStatement` object first. If it works correctly then it is something with the update hook code, but if it does not work, maybe we need to expose a `reset` function for prepared statements after indexes have changes.

**Comment by maksym-kyryliuk** [comment]
> Sorry, I was not on the computer, but just re-read your last comment. The queries are executed based on the [`sqlite3_update_hook`](https://www.sqlite.org/c3ref/update_hook.html) which means it will not execute at the end of the `executeBatch` but after each sql statement that touches the table. So yeah, it will include intermediate results. It is either a internal quirk of sqlite where specifying a text id needs to rebuild the index or somehow the internal prepared statement needs to be resetted before executing after an index has changed. That's why I keep saying, try it with a pure `prepareStatement` object first. If it works correctly then it is something with the update hook code, but if it does not work, maybe we need to expose a `reset` function for prepared statements after indexes have changes.

@ospfranco, I hope I understood correctly how to use the preparedStatement. To test I've updated the code of the delete function to execute preparedStatement immediately after executeBatch:
```
const commands: SQLBatchTuple[] = [
  ["DELETE FROM records WHERE ...", [id]],
  ["DELETE FROM transactions WHERE ...", [id]],
  ["DELETE FROM accounts WHERE id = ?", [id]]
];
db.executeBatch(commands);

const result = this.pureStatement.execute();
console.log(result.rows?._array);
```

In the result, I see the correct data without the deleted account. There are no errors here.

Was it correct using of what you described?

**Comment by ospfranco** [comment]
Should be something like

```ts
const p = db.prepareStatement('LONG COMPLEX SQL WITH SELECT a.id')
p.bind([YOUR PARAMS]);
let results = p.execute()

const commands: SQLBatchTuple[] = [
  ["DELETE FROM records WHERE ...", [id]],
  ["DELETE FROM transactions WHERE ...", [id]],
  ["DELETE FROM accounts WHERE id = ?", [id]]
];
db.executeBatch(commands);

// execute the prepared statement again, to make sure everything is correct
results = p.execute()
console.log(result.rows?._array);
```

**Comment by maksym-kyryliuk** [comment]
@ospfranco With your example it works like a charm: no errors and correct response.

The only difference in my case, is that I don't use `p.bind([YOUR PARAMS]);`, because I need to query everything from the table.

the SQL in prepareStatement is:
```
SELECT a.id, a.title,
  COALESCE(SUM(
    CASE
      WHEN r.type= 2 THEN COALESCE(r.converted_sum, r.sum)
      ELSE -COALESCE(r.converted_sum, r.sum) 
    END
  ), 0) AS sum
FROM accounts a
LEFT JOIN records r ON a.id = r.account_id
GROUP BY a.id
```

**Comment by ospfranco** [comment]
ok, then maybe is some artifact with the update hook firing too fast. If you can modify the example to reproduce the issue on a simplified version I will take a look ASAP.

**Comment by maksym-kyryliuk** [comment]
I'll let you know once push the updated example

**Comment by maksym-kyryliuk** [comment]
@ospfranco The reproducible example [is under the same link](https://github.com/maksym-kyryliuk/opsqliteIssue)

**Comment by ospfranco** [comment]
You might have to wait a couple of weeks :) currently traveling

**Comment by ospfranco** [comment]
It seems the problem is executing the query again in the middle of a transactions with deletes. Basically the update hook, tries to execute in between each of your statements and sqlite just kaputs itself. I've tried adding a mutex but to no avail since everything runs on the same thread and just skipping until the batch operation has finished is also no good since only updates trigger the reactive query.

This will require a fine more granular algorithm to avoid the race condition. Possibly, adding a combination of the commit hook with a queue

**Comment by ospfranco** [comment]
I've been reading a bit more about the update hook and the docs say this:

> The update hook implementation must not do anything that will modify the database connection that invoked the update hook. Any actions to modify the database connection must be deferred until after the completion of the sqlite3_step() call that triggered the update hook. Note that sqlite3_prepare_v2() and sqlite3_step() both modify their database connections for the meaning of "modify" in this paragraph.

https://www.sqlite.org/c3ref/update_hook.html

So I guess the current implementation of the reactive queries is wrong. I guess here the is "must be deferred until the completion of `sqlite3_step`. This will require a lot of re-engineering on how the callback is called.

**Comment by ayushneekhar** [comment]
I still seem to be encountering this issue, my query function is as follows:

  ```ts
  getCategoriesByUserReactively(
    userId: string,
    setter: () => void,
  ): Category[] {
    const query = 'SELECT * FROM categories WHERE user_id = ?';

    this.database.reactiveExecute({
      query,
      args: [userId],
      fireOn: [
        {
          table: 'categories',
        },
      ],
      callback: response => {
        console.log('line115', JSON.stringify(response.rows._array, null, 2));
        setter(response.rows._array);
      },
    });
  }```

Currently running "@op-engineering/op-sqlite": "^6.2.11", am I doing something wrong? As in the original issue reactiveQueries without any args works fine, the callback isn't triggered at all.

**Comment by ospfranco** [comment]
@ayushneekhar the original issue was fixed. Make sure you did a pod install if you updated from a new version. Otherwise please create a reproducible example.
