### ISSUE TITLE
Accessing db from SD Card

### ISSUE THREAD

**Issue by im-alihashmi14** [OP-Engineering/op-sqlite#12]
I am currently seeking guidance on the process of reading SQLite database (.db) files from an SD Card within the context of an Android application.

I am managing multiple databases ranging in size from 1 GB to 3 GB, and it is my preference not to store these databases within the assets folder. Instead, I am interested in understanding how to dynamically reference and utilize these databases without the necessity of storing them in the assets directory. Additionally, I aim to implement a mechanism to download these databases initially and subsequently place them in a designated folder for further utilization. Could you provide assistance in accomplishing this task?

**Comment by ospfranco** [comment]
Currently not possible, the package is [getting the file location from the OS APIs](https://github.com/OP-Engineering/op-sqlite/blob/main/android/src/main/java/com/op/sqlite/OPSQLiteBridge.java#L18). If you want this you will have to submit a PR. 

Before you go running implementing this I suggest you first propose a change to the API we can discuss/review and then implement. Remember the package needs to support both Android and iOS, so ideally you would put this behind a flag or something.

**Comment by im-alihashmi14** [comment]
Thank you for the prompt response. Is it possible to transfer files from the SD Card to the assets folder? I believe this might provide a means to access the database. I have limited experience with native development, so please disregard if this question seems naive. 😅

**Comment by ospfranco** [comment]
Sure you can, any of the fs libraries is capable of moving files around. It's better if you ask on StackOverflow though, I have little time to handle other requests atm.

**Comment by ospfranco** [comment]
Just released a new version, you can now pass an absolute path and the library will correctly detect it.

[See usage on the README](https://github.com/OP-Engineering/op-sqlite#passing-absolute-paths).
