### ISSUE TITLE
loadExtension [Error: Failed to open database: Exception in HostFunction: undefined symbol: arabic_tokenizer]

### ISSUE THREAD

**Issue by NaseemYE** [OP-Engineering/op-sqlite#121]
**Describe the bug**

**Versions:**

- OS and version: [mac 14.5 , android arm64-v8a - android 12]
- op-sqlite version: [^6.1.3]
- RN version: [0.74.3]
- New Architecture: [Yes]

I'm having trouble downloading plugins
First, I compiled the extension into the Android system using the following commands:

```

compile-android-arm64-v8a:
  $(NDK)/toolchains/llvm/prebuilt/$(HOST_TAG)/bin/clang -target aarch64-linux-android21 -shared -fPIC generate/sqlite3-arabic-tokenizer.c -o dist/android/arm64-v8a/sqlite3 -arabic-tokenizer.so

compile-android-armeabi-v7a:
  $(NDK)/toolchains/llvm/prebuilt/$(HOST_TAG)/bin/clang -target armv7a-linux-androideabi21 -shared -fPIC generate/sqlite3-arabic-tokenizer.c -o dist/android/armeabi-v7a/sqlite3 -arabic-tokenizer.so

compile-android-x86:
  $(NDK)/toolchains/llvm/prebuilt/$(HOST_TAG)/bin/clang -target i686-linux-android21 -shared -fPIC generate/sqlite3-arabic-tokenizer.c -o dist/android/x86/sqlite3-arabic -tokenizer.so

compile-android-x86_64:
  $(NDK)/toolchains/llvm/prebuilt/$(HOST_TAG)/bin/clang -target x86_64-linux-android21 -shared -fPIC generate/sqlite3-arabic-tokenizer.c -o dist/android/x86_64/sqlite3-arabic -tokenizer.so

```
Then I put them inside:
```

/android
	/app
		/src
			/main
				/jniLibs
					/arm64-v8a
						sqlite3-arabic-tokenizer.so
					/armeabi-v7a
						sqlite3-arabic-tokenizer.so
					/x86
						sqlite3-arabic-tokenizer.so
					/x86_64
						sqlite3-arabic-tokenizer.so


```
Then it was called by:

`db.loadExtension('sqlite3-arabic-tokenizer', 'arabic_tokenizer');`

But I have the following problem:

`[Error: Failed to open database: Exception in HostFunction: undefined symbol: arabic_tokenizer]`

Taking into account that I compiled it for Mac systems and used it via the sqlite terminal and it worked perfectly.

But when I use it within the application, I have the problem you mentioned

SQL query :

```
CREATE VIRTUAL TABLE articles_fts USING fts5(
    thread_id UNINDEXED,
    id,
    title,
    content,
    dateline UNINDEXED,
    content='articles',
    tokenize = "arabic_tokenizer",
);
```

package.json
```
"op-sqlite": {
	  "iosSqlite": false,
	  "fts5": true
	}
```

Extension files:
[sqlite3-arabic-tokenizer.zip](https://github.com/user-attachments/files/16185968/sqlite3-arabic-tokenizer.zip)

Files without compilition
https://github.com/GreentechApps/sqlite3-arabic-tokenizer

**Comment by ospfranco** [comment]
a few questions:

- did you use a try/catch? The [function](https://github.com/OP-Engineering/op-sqlite/blob/main/cpp/DBHostObject.cpp#L672) throws when something go wrong, though sqlite doesn't throw errors on load extension function.
- Is `arabic_tokenizer` the correct entry point for your extension?
- What command did you use on the sqlite terminal to load it?

Other than that, I don't really know what could be the problem. The library correctly packages other extensions and loads them correctly so it has to be something on your specific compilation process or packaging that is not quite working.

**Comment by ospfranco** [comment]
I can see in the README of the repo you posted they load the extension without modifying the entry point

https://github.com/GreentechApps/sqlite3-arabic-tokenizer

You should read on the usage of [extension loading](https://www.sqlite.org/c3ref/load_extension.html).

**Comment by NaseemYE** [comment]
I think entry_function_of_the_extension
It is 
`sqlite3_sqlitearabictokenizer_init`

I found it in the `sqlite3-arabic-tokenizer.h` file

When used the following appears

 [Error: Exception in HostFunction: [op-sqlite] SQL statement error on opsqlite_execute:
1 description:
no such table: articles]

Knowing that this table exists

I still don't quite understand the cause of the problem
Note: I edited the first post here

**Comment by NaseemYE** [comment]
Sorry, it was the function
`sqlite3_sqlitearabictokenizer_init`
I found it in the `sqlite3-arabic-tokenizer.h `file
Thank you
