### ISSUE TITLE
Bug: When using `libsql` and the `openSync` method, the embedded replica (local database) will not sync with the remote database

### ISSUE THREAD

**Issue by theorib** [OP-Engineering/op-sqlite#124]
**Describe the bug:**
When using op-sqlite with libsql (and Turso), the `openSync` method does not sync the Embedded Replica (local database) with the remote database. This renders the embedded replica unusable.

A few more things affect the implementation and usage of `openSync` to effectively use embedded replicas with op-sqlite:
- there is no exposed method equivalent to libsql's `sync()` method to manually sync the embedded replica with the remote database.
- when setting a database client with `openSync`, there is no way to set the `syncInterval` to automatically sync data to your embedded replica using libsql's the periodic sync feature.

I would happily open a PR but I'm not versed in C++ , I'm more than happy to help debug and test.

**Versions:**

- OS and version: building with MacOS 14.5 (23F79) for iOS 17.5
- op-sqlite version: 6.1.4
- RN version: 0.74.3
- New Architecture: Yes

**Reproducible example**
Clone the GitHub repo and follow the instructions outlined on the `README.md` file to get the a sample database running with Turso:
[https://github.com/theorib/op-sqlite-turso-expo-react-native.git](https://github.com/theorib/op-sqlite-turso-expo-react-native.git)

**Comment by ospfranco** [comment]
I don't see any way to pass a sync interval in the [C headers](https://github.com/tursodatabase/libsql/blob/main/bindings/c/include/libsql.h) so I don't think it is possible. However I just opened a PR that enables the `sync` call so you can replicate a sync interval in pure JS easily.

**Comment by ospfranco** [comment]
Released in version `6.2.11`

**Comment by ospfranco** [comment]
Released in `7.0.1`
