### ISSUE TITLE
Failed to compile in react-native-macos project

### ISSUE THREAD

**Issue by bear-ei** [OP-Engineering/op-sqlite#125]
**Describe the bug**
CompileC /Users/bearei/Library/Developer/Xcode/DerivedData/Bearei-cfkefzitawvsoiahawyfiooznfcf/Build/Intermediates.noindex/Pods.build/Debug/op-sqlite.build/Objects-normal/x86_64/OPSQLite.o /Users/bearei/Documents/code/bear/client/Bearei/node_modules/@op-engineering/op-sqlite/ios/OPSQLite.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'op-sqlite' from project 'Pods')

**Versions:**

- OS and version: MacOS 14.5 (23F79)
- op-sqlite version: 6.2.11
- RN version: 0.73.33
- New Architecture: No

**Reproducible example**
npx react-native-macos-init Initialises a new react-native-macos project. Failed at compile time.

**Comment by ospfranco** [comment]
Without an error cannot tell what's wrong. If you can create a reproducible example I can take a more detailed look.

**Comment by bear-ei** [comment]
https://github.com/bear-ei/op-sqlite-react-native-macos-example

This is a pristine [React Native for macOS](https://github.com/microsoft/react-native-macos) project. After installing dependencies and Pods, the issue can be reproduced by running `npx react-native run-macos`.

**Comment by ospfranco** [comment]
The app ran just fine for me
<img src="https://github.com/user-attachments/assets/30bfc53f-4fd8-49c7-941f-4ff51b61086d"
 width="300"/>

Did:
- clone the repo
- npm i
- cd macos
- pod install
- cd ..
- npx react-native run-macos

**Comment by bear-ei** [comment]
I have captured an error message through XCODE. `Cannot initialize a variable of type 'BOOL' (aka 'signed char') with an rvalue of type 'id _Nullable'`.

If possible, could you tell me what issues this might be related to? Many thanks.

![error](https://github.com/user-attachments/assets/a526e4fc-54da-4051-a9d9-d971807dc24a)

**Comment by ospfranco** [comment]
Hard to say, chatGPT has the following suggestions:

1. Check Xcode Version

Ensure that both machines are using the same version of Xcode. Differences in the compiler or SDK versions might cause discrepancies.

	•	Open Xcode and go to Xcode > About Xcode to check the version.

2. Check Project Settings

Verify that the project settings are identical on both machines.

	•	Compare Build Settings, Build Phases, and Build Rules.
	•	Ensure the same deployment target and architectures are selected.

3. Clean the Build

Try cleaning the build folder and rebuilding the project.

	•	In Xcode, go to Product > Clean Build Folder or press Shift + Command + K.

4. Check for Third-Party Libraries

Ensure that any third-party libraries or frameworks are correctly installed and configured.

	•	Verify that the necessary pods or dependencies are installed and up to date.
	•	If using CocoaPods, run pod install to ensure consistency.

5. Check Compiler and Language Settings

Ensure the compiler and language settings are consistent.

	•	In Build Settings, check Objective-C Language Dialect and C Language Dialect.
	•	Verify that Nullability settings are the same.

6. Compare Environment Variables

Check for any environment variables or path differences.

	•	Compare the output of env or printenv in the terminal on both machines.
	•	Ensure the PATH variable includes the correct paths for Xcode tools.

7. Verify Xcode Command Line Tools

Ensure the correct version of Xcode Command Line Tools is installed.

	•	Run xcode-select --install to install or update the Command Line Tools.

8. Check for Derived Data Issues

Sometimes, derived data can cause issues. Try deleting it.

	•	In Xcode, go to Window > Organizer > Projects, select your project, and delete the derived data.

**Comment by SamMade** [comment]
@bear-ei did you ever figure this out?  I'm seeing the same thing

Versions:

OS and version: MacOS 15.3.1 (24D70)
op-sqlite version: 11.4.8
RN version: 0.76.7
New Architecture: Yes

**Comment by bear-ei** [comment]
> [@bear-ei](https://github.com/bear-ei) did you ever figure this out? I'm seeing the same thing
> 
> Versions:
> 
> OS and version: MacOS 15.3.1 (24D70) op-sqlite version: 11.4.8 RN version: 0.76.7 New Architecture: Yes

I tried to follow up on this issue, but I didn't find a solution. I don't want to spend too much time on this library because it was only one of the libraries we were considering for our project. In the end, considering the actual situation of our own project, we chose to use ``MMKV``. It works well on ``react-native-macos``.

**Comment by ospfranco** [comment]
Just FYI react-native-macos does not support the new arch yet, if you got it to compile it could be through some random cached artifact but AFAIK it will break. Other than I can tell you I have tried op-sqlite on other rn-macos projects and it works just fine, you have something on your machine/project that is causing the issue. As I said, I tried your reproduction example and it compiled just fine in my machine, so it has to be some xcode version, clang version, or other project tooling that is causing the issues.

**Comment by ospfranco** [comment]
In any case, I just tried your reproducible example again, both with old arch and new arch and it is working fine from a clean copy. I'm also using the latest Xcode.

If you cannot provide a reproducible example, not much I can do.

![Image](https://github.com/user-attachments/assets/0dcdbae7-8d9e-481c-8adb-d969dab63482)

The error you are getting is basically saying you cannot assign a nullable (id _Nullable) to a non-nullable type (BOOL), so the compiler is doing extra checks and not casting the value to BOOl, this is valid normal obj-c so either your installed compiler, xcode or something else is mismatching and compiling with another compiler that does this extra check

Which clang compiler version do you have installed? How did you install it? Which Xcode version are you using?

**Comment by bear-ei** [comment]
> In any case, I just tried your reproducible example again, both with old arch and new arch and it is working fine from a clean copy. I'm also using the latest Xcode.
> 
> If you cannot provide a reproducible example, not much I can do.
> 
> ![Image](https://github.com/user-attachments/assets/0dcdbae7-8d9e-481c-8adb-d969dab63482)
> 
> The error you are getting is basically saying you cannot assign a nullable (id _Nullable) to a non-nullable type (BOOL), so the compiler is doing extra checks and not casting the value to BOOL. This is valid normal obj-c so either your installed compiler, Xcode or something else is mismatching and compiling with extra checks.
> 
> Which clang compiler version do you have installed? How did you install it? Which Xcode version are you using?

When I encountered this error before, due to the tight project schedule, I indeed did not spend enough time checking the root cause of the problem. 

Just now, I carefully reviewed the erroneous code section and found that there is a type mismatch issue in this part of the code. 

```'args' is an NSDictionary```, and the value obtained using the key ```@"overwrite" should be of NSNumber type```. 

Directly assigning it to a ```BOOL``` variable 'overwrite' causes a type mismatch because NSNumber is an object while ```BOOL``` is a primitive type, and they cannot be directly converted. 

I modified the code to ```BOOL overwrite = [args[@"overwrite"] boolValue];``` and now it compiles successfully. Although I am puzzled as to why your side could compile successfully, this modification indeed resolves the issue.


```
RCT_EXPORT_METHOD(moveAssetsDatabase
                  : (NSDictionary *)args resolve
                  : (RCTPromiseResolveBlock)resolve reject
                  : (RCTPromiseRejectBlock)reject) {
  // ...Other code...
  
  // Before modification
  // BOOL overwrite = args[@"overwrite"];
  
  // After modification
  BOOL overwrite = [args[@"overwrite"] boolValue];

  // ...Other code...
}
```

![Image](https://github.com/user-attachments/assets/2e9a394d-2eda-44d1-b686-162a16f6a301)

@SamMade This fix might be helpful for you.

**Comment by ospfranco** [comment]
yeah, but this is what I mean, there is no reason for the value inside to be a NSNumber, NSDictionary * is just a pointer with no information of the types contained, I don't know which react-native version you are using but boolValue will crash if the contained type is BOOL

**Comment by ospfranco** [comment]
Wait how are you calling this? This is not the same error you sent originally, now it sounds like you are getting a runtime error

**Comment by bear-ei** [comment]
First of all, this was the initial error. I encountered the original error by running a clean application using `npx react-native run-macos`. It was a clean project with only `op-sqlite` installed. Because I captured more detailed error reports, the second error message was obtained by running the application through Xcode to gather more information. Both methods failed during the native code compilation phase at startup.

Then, upon examining the portion of the `op-sqlite` source code where the error occurred, I found that the usage `BOOL overwrite = args[@"overwrite"]` was problematic. In Objective-C, `NSDictionary` cannot directly store primitive data types (such as `BOOL`, `int`, `float`); all values must be objects (such as `NSNumber`, `NSString`). React Native has a clear definition for how it maps parameter types between JavaScript and native code: `boolean` is mapped to `NSNumber`. When JavaScript calls a native method, the parameter `overwrite: true` is automatically converted to an `NSNumber` object. Therefore, `args[@"overwrite"] `cannot be a primitive `BOOL` type because `NSDictionary` can only store objects.

So, the core points of this issue are the following:

- `BOOL` is a primitive type and cannot be directly stored in an `NSDictionary`.
- `NSNumber` is an object type used to encapsulate primitive types such as `BOOL`.
- `React Native` automatic type conversion ensures that boolean values are correctly converted to `NSNumber`. 

Therefore, `BOOL overwrite = args[@"overwrite"]` will result in a type checking error.

Of course, I also noticed another point: your device seems to be using an M-series chip. This error typically occurs on Intel-based devices. However, the core issue lies in the usage of `BOOL overwrite = args[@"overwrite"]`, which caused the error. Using `BOOL overwrite = [args[@"overwrite"] boolValue]` can fix it.

**Comment by ospfranco** [comment]
All booleans are stored as integers in most programming languages, assigning `BOOL my_bool = 1` is valid. You absolutely can store BOOLs in a NSDictionary, here is the attached debugger:

![Image](https://github.com/user-attachments/assets/fbe7c252-0b5d-4904-85a1-5e4a915c8107)

Unless you are using and outdated compiler or some other compiler flag that stricter.

I asked how are you calling the `moveAssetsDatabase`, check out the docs, the value needs to be a boolean, maybe your transpiler configuration is converting your JS and passing a number somehow.

```ts
    moveAssetsDatabase({
      filename: 'blah',
      overwrite: true,
    });
```

In any case, I cannot help further if there is no reproducible example or you cannot determine the source of your issues. Going to close this as I have already spent enough time trying to debug the issue. If any one else is facing the issue, create a reproducible example with more information, compilers, Xcode, RN version, make sure you have not installed a clang compiler through brew, etc.
