### ISSUE TITLE
Recommended configuration for common projects

### ISSUE THREAD

**Issue by pavelustenko** [OP-Engineering/op-sqlite#134]
Can we state that following configuration which can be found in example app is the most suitable for common projects?
```
"op-sqlite": {
    "sqlcipher": false,
    "crsqlite": false,
    "performanceMode": "2",
    "iosSqlite": false,
    "fts5": true,
    "libsql": false
  }
```

**Comment by ospfranco** [comment]
You can omit all the false keys, performanceMode 2 and fts5 should fit most projects.
