### ISSUE TITLE
Question about result codes

### ISSUE THREAD

**Issue by akserg** [OP-Engineering/op-sqlite#136]
Hi @ospfranco,

Many SQLite functions return integer result codes like SQLITE_OK, SQLITE_ERROR, SQLITE_BUSY, etc., which are useful for analysis and making recovery decisions. I noticed in your library that these codes are replaced by error messages instead. Was this choice intentional, or was there another reason behind it?

**Comment by ospfranco** [comment]
I was returning the error codes but most people do not look at them or understand them. Feel free to open a PR to re-introduce them though.

**Comment by akserg** [comment]
Sure. Here are two possible implementation approaches:

1. **Modify the `BridgeResult` structure by adding an extra parameter**, followed by making the necessary updates in all invocation methods. This approach involves significant implementation effort and requires extra caution to avoid breaking the existing functionality.

2. **Introduce an additional method to invoke `sqlite3_errcode`,** which retrieves the most recent error code generated by an SQLite routine. This approach has a lower implementation effort and involves the following steps:

   - **Client-side:**
     - Add the method definition to the `DB` type.
     - Implement the method in the `OPSQLiteProxy` type.

   - **Native-side:**
     - Add the method definition to `bridge.h`.
     - Implement the method in `bridge.cpp`.

@ospfranco,  what do you think?

**Comment by ospfranco** [comment]
Looks very chatGPT, but no to the second. Multithreading makes retrieving error codes unreliable. You need to modify the responses on each call to the sqlite interfaces and their respective JSI implementations.

**Comment by akserg** [comment]
Thank you.
