### ISSUE TITLE
React-native asg017/sqlite-vec support

### ISSUE THREAD

**Issue by devYonz** [OP-Engineering/op-sqlite#138]
Add sqlite-vec extension support with op-sqlite to support vector and embedding similarity features. https://github.com/asg017/sqlite-vec and op-sqlite belong together since both have minimal dependencies and would make mobile deployment of vectors in mobile effortless.  We are looking to migrate from expo-sqlite to an sqlite solution that supports vectors.

**Comment by ducpt-bili** [comment]
+1 for this feature, already watching the sqlite-vec, that @ospfranco is working on this feature.
https://github.com/asg017/sqlite-vec/pull/91

**Comment by ospfranco** [comment]
It's already merged and released

**Comment by ducpt-bili** [comment]
hi @ospfranco , it will work out of the box, no need for more documents to guide how to setup or use it right?
Thank you.

**Comment by ospfranco** [comment]
Read the docs
