### ISSUE TITLE
[question] what is the best way to export database?

### ISSUE THREAD

**Issue by iliapnmrv** [OP-Engineering/op-sqlite#139]
Hello! Thank you for this library!
```ts
await Share.open({
    url: db.getDbPath(),
    failOnCancel: false,
    type: 'application/x-sqlite3',
});
```
I'm trying to export db file but .sqlite file does not contain relevant data. Do you have any ideas? 
I tried using pragmas but it did not help
```ts
await db.executeRawAsync(`PRAGMA synchronous = FULL`);
```

**Comment by Caligone** [comment]
I’m experiencing a similar issue with an empty database file when attempting to export it, even after closing the database. If I restart the application and try exporting the file again, the database is no longer empty.

It seems that the data is not being persisted to the filesystem until the application is fully closed or unloaded.

Has a solution been identified for this issue?

**Comment by ospfranco** [comment]
Seems unlikely that db is not persisted, you probably want to copy it to the documents folder before sharing though, since the file system is sandboxed it might be refusing to just read from the default location.

**Comment by ospfranco** [comment]
You guys might be doing something wrong, just tested this:

```ts
const shareDb = async () => {
    try {
      const db = open({
        name: 'shareableDb.sqlite',
      });

      await db.execute(
        'CREATE TABLE IF NOT EXISTS test (id INTEGER PRIMARY KEY, name TEXT)',
      );
      await db.execute("INSERT INTO test (name) VALUES ('test')");
      const res = await db.execute('SELECT * FROM test');
      console.log(res);

      await db.close();
      await Share.open({
        url: 'file://' + db.getDbPath(),
        failOnCancel: false,
        type: 'application/x-sqlite3',
      });
    } catch (e) {
      console.log(e);
    }
  };
```

And the file on my mac

![OSP 000364](https://github.com/user-attachments/assets/ff5d8a55-06cc-4432-a6fe-9a708828c457)

**Comment by Caligone** [comment]
It turns out I was indeed making a mistake. I'm using `PRAGMA journal_mode = WAL`, and after carefully reviewing the related documentation, I added a manual checkpoint to force synchronization with the following command: `PRAGMA wal_checkpoint(FULL)`.
