### ISSUE TITLE
[Question] Does your library support Watermelon or Powersync, the offline first solution?

### ISSUE THREAD

**Issue by ducpt-bili** [OP-Engineering/op-sqlite#141]
Hi @ospfranco , just want to ask that your library can integrate with two offline first solution WatermelonDb or Powersync.
You did really great job with op-sqlite.

Thank you

**Comment by ospfranco** [comment]
Watermelon has it's own SQLite driver which is already JSI. Power sync is a complete different product AFAIK.

**Comment by ducpt-bili** [comment]
hi @ospfranco , i have 2 question more.
1. Does Watermelon sqlite is good/bad compare to op-sqlite?
2. Can we using op-sqlite in Watermelon db using db adapter or something else?
Have a good day @ospfranco , really appriciate your work on op-sqlite. 
Thanks

**Comment by ospfranco** [comment]
No, watermelon it's a separate library, closing this.

**Comment by iliapnmrv** [comment]
@ducpt-bili i moved from watermelon db and i'm happy with this library and my users are happy too. This library has high level of abstraction and it gives you a ton of flexibility. I can share my experience if you have any questions

**Comment by ducpt-bili** [comment]
hi @iliapnmrv , for more clear, what are your meaning by "moved from watermelondb", do you not using it and using some replace tool like powersync? Thank you.

**Comment by iliapnmrv** [comment]
@ducpt-bili  We no longer use WatermelonDB. Instead, I implemented server sync using REST APIs. For data requests, you can use RTK Query or React Query with their polling functionality and also websockets, which has worked perfectly for my needs

**Comment by iliapnmrv** [comment]
Sorry if im being unclear but I do use op-sqlite as offline first solution.
I have the flow like this
1. I request data from server (around 100k rows in peak)
2. User uses app completely offline
3. as soon as internet connection establishes, I sync data using REST apis (both sending and receiving data from server)

I do not use any ORMs, I have quite complex SQL queries, I dont think orms could handle it. 

If you have any questions, don't hesitate to ask

**Comment by rkistner** [comment]
For the PowerSync side, we're tracking the status of supporting op-sqlite here: https://github.com/powersync-ja/react-native-quick-sqlite/issues/42
