### ISSUE TITLE
Calling .close() closes all existing DB Connections?

### ISSUE THREAD

**Issue by On2it-Clifford** [OP-Engineering/op-sqlite#146]
**Describe the bug**
```
let db1 = open({ name: 'test' });
let db2 = open({ name: 'test' });

db1.close();
db2.execute('Anything');
```
db2 will throw 'Error: Exception in HostFunction: [OP-SQLite] DB is not open' exception even thou I closes only the first connection.

**Versions:**

- OS and version: Android 14 (SDK 34)
- op-sqlite version: 7.4.3
- RN version: 0.73.8

**Comment by ospfranco** [comment]
No, this is a bug, it's unlikely you need two connections to the same db in your JS but I will take care of it anyways

**Comment by ospfranco** [comment]
Allowing multiple clean connections to the DB would require far more retooling than I have time for. I have now disabled it. If you try to open a new connection to the same DB in JS it will throw an exception.

It will be released with the next major version.

https://github.com/OP-Engineering/op-sqlite/pull/142

**Comment by On2it-Clifford** [comment]
@ospfranco , The reason I asked for this is because I have multiple backend jobs running at the same time. Example:
Scheduler A: Every 5 seconds will query DB, Table A and do some task
Scheduler B: Every 5 seconds will query DB, Table B and do some task

The problem is that occasionally, when both task run at the same time, one of the scheduler will closes the other scheduler's connection when it completes it task by calling .close, and this will cause the other scheduler that has yet to complete its task to have it's DB connection closed due to calling .close will close every single opened DB.

My example posted there is just to have a simple test case to replicate the issue that I am currently facing right now.

**Comment by ospfranco** [comment]
You don't need multiple connections for this. Just use executeAsync, tasks run on separate threads.

**Comment by ospfranco** [comment]
On the new version that will be released soon, you just need `execute` which is now async, there are no more sync versions.

**Comment by On2it-Clifford** [comment]
Yes @ospfranco, initially I do not close db connection and reuse them, it is working fine. But this will cause memory leak, where each query will consume the memory and does not release it if I do not call .close() and eventually it will crash the app when the memory is too low.

**Comment by On2it-Clifford** [comment]
You can do a simple test where you open a db connection and use a while(true) loop that constantly query something using the same db connection without .close(), the memory never get released until we kill the app.

**Comment by ospfranco** [comment]
Interesting, the new version should help maybe. Objects returned by the normal `execute` are no longer HostObjects so they can be properly cleaned. Give the 8.0.0-beta0 a try and if not open a new issue. No memory leaks should happen.

**Comment by On2it-Clifford** [comment]
Alright @ospfranco I will test it out and let you know again, thanks.

**Comment by ospfranco** [comment]
8.0.1 is out, give that one a try

**Comment by On2it-Clifford** [comment]
Just had a quick test on 8.0.0-beta0, seems to be working very fine with no leaks at all. Will try with 8.0.1 again later. Thanks for the quick response.

**Comment by 0cothucluc** [comment]
@ospfranco I'm facing ` [Error: Exception in HostFunction: [OP-SQLITE] Only one connection per database is allowed, db name: abc`, when I open app gain, it sometimes throw the exception, what is the best practice for this case? 
![image](https://github.com/user-attachments/assets/7b405642-30a9-444b-9e07-a912e48afc68)

**Comment by ospfranco** [comment]
Don't close the connection, just create one per app start

**Comment by 0cothucluc** [comment]
so I just need to open the connection when app starts right?

**Comment by ospfranco** [comment]
Read the docs, you also need to await the execute call

**Comment by 0cothucluc** [comment]
I added `.then()` for `execute` call
The docs u just say use `.close` to close the connection

**Comment by ospfranco** [comment]
Your app initialization code is wrong. When your app starts/hot reload is trying to create the DB connection again, which is wrong. I cannot tell you what's wrong because I don't have access to your code. Just create the connection once. Don't put it in a function just in a db.ts file create it at the module level:

```ts
// db.ts
export const db = open({...})
```

Read the docs carefully.

**Comment by 0cothucluc** [comment]
I got it, I put `.open` in `useEffect()`, thx for fast reply
