### ISSUE TITLE
Hitting alot of bad_variant_access after updating to 8.0.1

### ISSUE THREAD

**Issue by On2it-Clifford** [OP-Engineering/op-sqlite#148]
Hi @ospfranco , our project starting getting alot of bad_variant_access after updating to 8.0.1 for many different queries
but this does not happen to older 7.X.X version. Any idea what could have caused it?

**Comment by ospfranco** [comment]
Probably a bug, if you can create a reproducible example I'll take a look

**Comment by On2it-Clifford** [comment]
@ospfranco , I figured out what happened, previously the query parameters accept boolean values like false/true but now I'm forced to use back the bit value 0/1. Is this intended?

**Comment by ospfranco** [comment]
Probably not :) give me a snippet and I'll take a look

**Comment by On2it-Clifford** [comment]
You may try the below, the second one will hit bad_variant_access
```
(async () => {
            let db = OPSQLiteUtil.openDBConnection();
            let result1 = await db.execute(`SELECT ?`, [1]);
            console.log(result1.rows?._array);
            let result2 = await db.execute(`SELECT ?`, [true]);
            console.log(result2.rows?._array);
})();
```

**Comment by ospfranco** [comment]
Fixed it. `8.0.2` is being released. Give it a try once it finishes.

https://github.com/OP-Engineering/op-sqlite/actions/runs/10933644012/job/30352443552

**Comment by On2it-Clifford** [comment]
Thanks @ospfranco , it is working fine now in version 8.0.2.
