### ISSUE TITLE
Build error when react native is build from source

### ISSUE THREAD

**Issue by pigeonmal** [OP-Engineering/op-sqlite#150]
**Describe the bug**
I modified react native, so I must build from source. (React native is modified with patch, so inside node_modules folder). When I try to build app with opsqlite as dependency i got multiple errors, this is the first :
`C/C++: ld.lld: error: undefined symbol: facebook::jsi::HostObject::~HostObject()
C/C++: >>> referenced by SmartHostObject.h:13 `. It's like jsi is not definded ?
The errors are not from my patches, because I try with 0 modification, only build from source, and got the same errors.

**Versions:**

- OS and version: Android build
- React native : 0.75.3
- op-sqlite version: 8.0.2

**Link Reproducible example**
Just add this inside your settings.gradle : 
```
includeBuild('../node_modules/react-native') {
	dependencySubstitution {
        substitute(module("com.facebook.react:react-android")).using(project(":packages:react-native:ReactAndroid"))
        substitute(module("com.facebook.react:react-native")).using(project(":packages:react-native:ReactAndroid"))
        substitute(module("com.facebook.react:hermes-android")).using(project(":packages:react-native:ReactAndroid:hermes-engine"))
        substitute(module("com.facebook.react:hermes-engine")).using(project(":packages:react-native:ReactAndroid:hermes-engine"))
    }
}
```
And build

**Comment by ospfranco** [comment]
This goes beyond the scope and time of what I do to maintain the library, so you are better off asking on StackOverflow.

**Comment by ospfranco** [comment]
you can modify `node_modules/@op-engineering/op-sqlite/android/CMakeLists.txt` yourself and try to figure out what the problem is, but the module is not doing anything special and I'm not an expert in the build system of RN itself, so no idea what could be wrong.

**Comment by zhouzh1** [comment]
I encountered this issue as well and maybe the change in this [PR](https://github.com/OP-Engineering/op-sqlite/pull/269) can resolve it, at least it successfully helped me.
