### ISSUE TITLE
No info about threading

### ISSUE THREAD

**Issue by gentlee** [OP-Engineering/op-sqlite#158]
**Describe the bug**
1) No information about threading of this lib in docs. At what thread is everything executed?
2) Performance bench is overall time I guess, but RN JS thread total work time is often much more valuable in all such solutions as it freezes interaction with UI when JS thread is working. E.g. if sqlite blocks js thread more than async storage, then async storage is much better for fps of the app, even if overall executes longer.

**Comment by ospfranco** [comment]
Read the docs, threading is explained there. JS is not blocked at all.
