### ISSUE TITLE
Row HostObjects with default setters do not allow setting properties

### ISSUE THREAD

**Issue by ammarahm-ed** [OP-Engineering/op-sqlite#16]
It's possible that you would try to set a property on the resulting rows as they get referenced elsewhere in an application. Right now this is not possible and throws an error if you try `rows[0].customProperty = 100`.

The other solution might be to copy the host object values into a normal object but that means you lose he benefit of using `HostObjects` altogether.

**Comment by ospfranco** [comment]
I've implemented the setter method on the HostObjects. Released under `2.0.8`. Enjoy!
