### ISSUE TITLE
Query not working 

### ISSUE THREAD

**Issue by Gul7333** [OP-Engineering/op-sqlite#160]
I have table Brands
When I run execute("Select * from Brands") it work perfectly

But when I add extra SQL for sorting or order by Ascending the query give io error
Like "Select * From Brands ORDER BY Brand-name ASC"

I have checked multiple time and changed query but not working

**Comment by Gul7333** [comment]
My project has personal data

You can create a db which has Brand table containing three column (Brandname Price ingredients)

It is pre-populated db, use movedatbase function and execute query
When you  add extra params to sql query like order by brandname ,,it will throw I/o error
Simple query like select * from Brand will work

**Comment by Gul7333** [comment]
My project has personal data

You can create a db which has Brand table containing three column (Brandname Price ingredients)

It is pre-populated db, use movedatbase function and execute query
When you  add extra params to sql query like order by brandname ,,it will throw I/o error
Simple query like select * from Brand will work

**Comment by ospfranco** [comment]
Closing this, this is not an error with the library, probably with your table and your fields and also don't have the time to create a reproducible example myself.
