### ISSUE TITLE
Warning during commit or rollback of the transaction - "No transaction is active"

### ISSUE THREAD

**Issue by maksym-kyryliuk** [OP-Engineering/op-sqlite#164]
**Describe the bug**
After updating to the 9.2.2, every time I manually commit or roll back the transaction I am getting a warning:

![image](https://github.com/user-attachments/assets/eb74b2ec-c8f4-413f-b556-d1021187aba0)

- op-sqlite version: 9.2.2
- RN version: 0.73.4

To reproduce the issue is enough to use code from documentation:

```
await db.transaction((tx) => {
  const { status } = await tx.execute(
    'UPDATE sometable SET somecolumn = ? where somekey = ?',
    [0, 1]
  );

  await tx.rollback();
});
```

```
await db.transaction((tx) => {
  const { status } = await tx.execute(
    'UPDATE sometable SET somecolumn = ? where somekey = ?',
    [0, 1]
  );

  await tx.commit();
});
```

```
await db.transaction(async tx => {
  try {
    const {status} = await tx.execute(
      "UPDATE sometable SET somecolumn = ? where somekey = ?",
    [0, 1]
  );

    throw new Error('Random Error!');
  } catch (error) {
    tx.rollback();
  }
});
```

My configuration:
```
  "op-sqlite": {
    "sqlcipher": false,
    "crsqlite": false,
    "performanceMode": "2",
    "sqliteFlags": "-DSQLITE_DQS=1",
    "libsql": false,
    "iosSqlite": false,
    "fts5": true
  }
```

**Comment by ospfranco** [comment]
Can you create a reproducible example? All the tests are passing

**Comment by maksym-kyryliuk** [comment]
@ospfranco Sure, here is the [link to the example](https://github.com/maksym-kyryliuk/opsqliteIssue).


Load the app, and press the "Go to list" button. On the next screen, you will see 2 buttons:

1. **Add category with records** - will start a transaction and call tx.commit() in the end
2. **Test error** - will start a transaction, throw an error, and in the catch will call tx.rollback().

Both of them leads to the warning below:
![image](https://github.com/user-attachments/assets/528a7d8c-b6b5-49e9-a579-d4c6ee9c5ccd)

**Comment by maksym-kyryliuk** [comment]
Despite the warning above, the logic seems to work correctly for both commit and rollback. But this warning appears every time now for these cases.

**Comment by maksym-kyryliuk** [comment]
Also there are two logs seems wasn't removed from the release:

```
 LOG  BEFORE FLUSH
 LOG  AFER FLUSH
```

Link: https://github.com/OP-Engineering/op-sqlite/blob/main/src/index.ts#L352

**Comment by ospfranco** [comment]
You have to await the commit or the rollback. All sql operations are now async. After changing no warning is shown.

![OSP 000431](https://github.com/user-attachments/assets/55cd991a-3ca5-449e-9a1d-3cff41db0c55)
