### ISSUE TITLE
Remove log lines

### ISSUE THREAD

**Issue by talaikis** [OP-Engineering/op-sqlite#167]
```js
console.log('BEFORE FLUSH');
enhancedDb.flushPendingReactiveQueries();
console.log('AFER FLUSH');
```

**Comment by ospfranco** [comment]
This is removed in the latest version.

**Comment by talaikis** [comment]
> This is removed in the latest version.

Latest - @next? Because this is on 9.2.2.

**Comment by ospfranco** [comment]
Ah sorry, my bad, forgot to publish. `9.2.3` is building and will be released soon
