### ISSUE TITLE
Driver for Drizzle ORM

### ISSUE THREAD

**Issue by terry-fei** [OP-Engineering/op-sqlite#17]
I’m trying to implement the op-sqlite driver for Drizzle ORM, the biggest issue is that Drizzle requires a `raw` interface like better-sqlite3, it return rows as arrays instead of objects
https://github.com/WiseLibs/better-sqlite3/blob/HEAD/docs/api.md#rawtogglestate---this
https://github.com/drizzle-team/drizzle-orm/blob/main/drizzle-orm/src/better-sqlite3/session.ts#L146

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/OP-Engineering) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/OP-Engineering/op-sqlite/issues/17">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/17/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/17/pledge.svg">
</picture>
</a>

**Comment by ospfranco** [comment]
if you don't mind some performance penalty you can just implement this on the typescript side. On the index.ts you can just add a method or something that just iterates over the results and returns them as rows. Or am I misunderstanding you?

**Comment by ospfranco** [comment]
PRs are welcome, if not I would be willing to add the feature if you are willing to sponsor the work.

**Comment by ospfranco** [comment]
Yeah, my comment is valid. This are not normal JavaScript objects, these are JSI HostObjects, everything is implemented natively in C++ and the data is stored in a std::vector. Order will not change.

**Comment by AlexBlokh** [comment]
I see, than simple `Object.values()` should be just fine, thanks!

**Comment by XantreGodlike** [comment]
`Object.value` is not working for host objects.
```ts
const copyJsiHostObject = <T extends object, TKeys extends keyof T>(
  obj: T,
  fields?: readonly TKeys[],
): Pick<T, TKeys> => {
  const result = {} as T;
  for (const key of fields ?? Object.keys(obj)) {
    // @ts-expect-error
    result[key] = obj[key];
  }
  return result;
};
```

**Comment by XantreGodlike** [comment]
`Object.keys` is working

**Comment by octalpixel** [comment]
@XantreGodlike do you happen to have repo where you have implemented it ?

**Comment by XantreGodlike** [comment]
Nope, I didn't implement it. If you would - it's better to provide PR than creating your own repo

**Comment by garygcchiu** [comment]
https://x.com/DrizzleORM/status/1735220775773208952?s=20 👀

**Comment by RomanNabukhotnyi** [comment]
Hi! I'm writing a op-sqlite driver for  Drizzle ORM and I can’t map the result correctly because I’m faced with the problem of the lack of an api that returns raw data (array of arrays).

An example of why this is necessary:
```
import { open } from '@op-engineering/op-sqlite';

const db = open({
  name: 'db',
});

// create tables
db.execute('create table if not exists users (id integer primary key, name text)');
db.execute('create table if not exists items (id integer primary key, done integer, value text, userId integer)');

// insert users
db.execute('insert into users (id, name) values (?, ?)', [11, 'user1']);
db.execute('insert into users (id, name) values (?, ?)', [22, 'user2']);
db.execute('insert into users (id, name) values (?, ?)', [33, 'user3']);

// select users
db.execute('select * from users');

result: [{"id": 11, "name": "user1"}, {"id": 22, "name": "user2"}, {"id": 33, "name": "user3"}]

// insert items
db.execute('insert into items (id, done, value, userId) values (?, ?, ?, ?)', [1, 0, 'item1', 11]);
db.execute('insert into items (id, done, value, userId) values (?, ?, ?, ?)', [2, 0, 'item2', 22]);
db.execute('insert into items (id, done, value, userId) values (?, ?, ?, ?)', [3, 1, 'item3', 33]);

// select items
db.execute('select * from items');

result: [{"done": 0, "id": 1, "userId": 11, "value": "item1"}, {"done": 0, "id": 2, "userId": 22, "value": "item2"}, {"done": 1, "id": 3, "userId": 33, "value": "item3"}]

// join
db.execute('select items.id, users.id from items left join users on items.userId = users.id');

result: [{"id": 1}, {"id": 2}, {"id": 3}] <---
```

**Comment by ospfranco** [comment]
@RomanNabukhotnyi Busy with paid work. As stated, if anyone is willing to sponsor the work I can create a function call that returns pure arrays, otherwise converting the objects in JS is your alternative for now

https://github.com/OP-Engineering/op-sqlite/issues/17#issuecomment-1837133945

**Comment by garygcchiu** [comment]
Drizzle Expo driver released: https://orm.drizzle.team/docs/get-started-sqlite#expo-sqlite

**Comment by ospfranco** [comment]
I've created a funding goal for this issue, once it is reached I will take care of it

https://polar.sh/OP-Engineering/op-sqlite/issues/17

**Comment by ospfranco** [comment]
Thank you @ospfranco for contributing to close this issue! ⭐

The rewards from this issue, totalling $150, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
