### ISSUE TITLE
[Bug]: SyncInterval parameter should be mandatory or have a default value with the openSync method

### ISSUE THREAD

**Issue by leoalves** [OP-Engineering/op-sqlite#170]
### What happened?

When trying to create the clent with the `openSync` libsql method without passing the `syncInterval` parameter, the app crashes.

When passing it all works as expected.

This value should be either mandatory or have a default value.

Thanks,

### op-sqlite version

lbsql:true in package.json

### React Native version

Expo SDK 51

### Reproducible Example

If needed I can create one

**Comment by ospfranco** [comment]
Ah, interesting, didn't realize a value was needed or maybe something changed on the last versions of libsql. 

@haaawk what would be a good default value? Or should the developer always pass a value?

**Comment by haaawk** [comment]
It seems to have default of 0.0 in libsql JS client @ospfranco 
https://github.com/tursodatabase/libsql-js/blob/f941c5dd139f22ea9a297fb0a87b2b1362a1f9c2/promise.js#L81

**Comment by ospfranco** [comment]
then 0.0 it is, I'll release a new version shortly

**Comment by leoalves** [comment]
Wow. That was quick.
Just checked and it's working. Thanks

PS: I couldn't find the docs site in the repo to submit a PR. But if you could add to the docs that the default value is 0 (disabled).  And that the unit is in `seconds`.  At least that is what I think it is from my testing. Maybe @haaawk can confirm.  I think it would make it clear to the users.

Thanks again.

**Comment by haaawk** [comment]
It is in seconds.

**Comment by ospfranco** [comment]
Docs have been updated
