### ISSUE TITLE
[Request]: Bring back sync execute

### ISSUE THREAD

**Issue by pranshuchittora** [OP-Engineering/op-sqlite#173]
### What do you need?

Hey, I am using op-sqlite and in the newest version the `execute` api was changed from sync to async. 
My use-case requires sync query execution in some cases which can't be changed to async. 

https://github.com/OP-Engineering/op-sqlite/commit/1dbc8289e1a04841b1ae08b7fbbf3c849a3454a2#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R127

Is there any possibility to bring back the sync execute? or any workaround for the same?

Thanks

**Comment by ospfranco** [comment]
@rflopezm

Here was the change:

https://github.com/OP-Engineering/op-sqlite/pull/142/files#diff-cd0866c167878907e99d1e94024bc05e6f673d0e5228bf11448932f2aaa4d0c2L320

Now there are a couple of differences, before you go re-implementing this interface:

- Don't use `SmartHostObject` or `execute_with_host_objects`, the abstraction will cost too much on runtime, use the same as [current execute](https://github.com/OP-Engineering/op-sqlite/blob/main/cpp/DBHostObject.cpp#L398) but just don't execute it in a thread.
- Create a test (or maybe some tests cases) on `queries.spec.ts`. Make sure it returns the correct data
- Also create the same function for libsql. The tests already run automatically here, so as soon as you have created the test on `queries.spec.ts` it will let you know if something is missing.
- No need to modify the transactions for now. It's too much work to keep both interfaces working within the async context and now it might mess up with reactive queries. Bringing a simple `.execute` should be enough.
- If you need more info on interacting with the JSI there are guides and tutorials [on my website](https://ospfranco.com/post/2023/08/15/jsi-cheatsheet-part-3-jsi-api-reference/)

**Comment by pranshuchittora** [comment]
Thanks!
