### ISSUE TITLE
[Request]: RN 0.76 Support

### ISSUE THREAD

**Issue by jamesthomp** [OP-Engineering/op-sqlite#174]
Thanks for this excellent library.
It looks like RN 0.76 has made a breaking change to the android CMakeLists file that needs to be handled as there is a build error with RN 0.76:

```
CMake Error at CMakeLists.txt:19 (add_library):
    Target "op-sqlite" links to target "ReactAndroid::turbomodulejsijni" but
    the target was not found.  Perhaps a find_package() call is missing for an
    IMPORTED target, or an ALIAS target is missing?
```

There is more detail about the change at https://github.com/react-native-community/discussions-and-proposals/discussions/816

**Comment by ospfranco** [comment]
awesome, thanks for the link, the change looks easy enough, let me give it a try
