### ISSUE TITLE
[Bug]: Weird reactiveExecute behavior in useEffect and useState

### ISSUE THREAD

**Issue by shovel-kun** [OP-Engineering/op-sqlite#177]
## Description
I've observed two bugs when using reactiveExecute with useEffect and useState:

1. unsubscribe does not work when unmounting, but will work elsewhere. 
2. setting unsubscribe to a useState will cause unsubscribe to run.

## Motivation
What I want to do is:
- Mount a component
- Have it listen to changes in DB for as long as component is mounted
- Stop listening to changes in DB when component is unmounted.
- No duplicate listeners.

Does anyone have a workaround that allows me to accomplish the above?

### op-sqlite version

9.2.6

### React Native version

New Arch 0.76, but can be reproduced on older RN versions. 

### Reproducible Example

https://github.com/shovel-kun/op-sqlite-useeffect-repro

See instructions in `App.tsx` for repro.

### Expected logs:
```
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 LOG  Effect unmounting
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 LOG  Effect unmounting
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 ```
 
 ### Actual logs: 
 ```
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 LOG  Effect unmounting
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 LOG  Callback ran!
 LOG  Effect unmounting
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 LOG  Callback ran!
 LOG  Callback ran!
 ```

**Comment by ospfranco** [comment]
You have to await the execute

https://github.com/shovel-kun/op-sqlite-useeffect-repro/blob/main/App.tsx#L77

**Comment by shovel-kun** [comment]
@ospfranco Added the fix, but the reactiveExecute still doesn't unsubscribe on unmount.

```
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 LOG  Effect unmounting
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 LOG  Callback ran!
 LOG  Effect unmounting
 LOG  Effect mounted
 LOG  Pressed!
 LOG  Callback ran!
 LOG  Callback ran!
 LOG  Callback ran!
 ```

**Comment by ospfranco** [comment]
ah, I see it now. Give me some minutes I'll take a look.
