### ISSUE TITLE
jsonb decoding

### ISSUE THREAD

**Issue by joprice** [OP-Engineering/op-sqlite#191]
I'm curious how jsonb columns are meant to be handled. If I pass a js array of objects as one of `execute`'s params, I get `Unknown JSI ArrayBuffer to variant value conversion, received object instead of ArrayBuffer`. If I encode the json to a string, it inserts, but then upon reading the value, I get a string back instead of json. This made me think that it was being stored as json, but json queries like `select json_extract(tokens, '$[1]') from articles` work. I'm not sure if this is a bug in the api, a missing feature, or if I'm supposed to be doing something else when using the api with jsonb data to get it to be json on the way in and json on the way out. If this is the expected behavior, I can just insert as string and then use `JSON.parse` on the value initially before parsing it into a domain object.

**Comment by ospfranco** [comment]
Good question. Passing array/object definitely won't work, those are cast to ArrayBuffers internally and it's meant for the ArrayBuffer/Blob use case. Did you turn on the JSONB extension? Is it an extension? Not sure how this is supposed to work.

**Comment by ospfranco** [comment]
Ah, intersting, it seems on the latest versions one can store JSON as a blob and save some time on the conversion:

https://fedoramagazine.org/json-and-jsonb-support-in-sqlite-3-45-0/

There are no jsonb columns, sqlite only has the basic data types and then when the query is executed is the column interpreted as a different value.

So yeah, basically, you need to convert your object to a string or a ArrayBuffer when you are running your insert. You are misusing the api, at no point it is stated you can pass an object and it will be converted to string/blob for you.

**Comment by joprice** [comment]
Thank you for the quick response! That explains the current behavior. I'll parse the string first and then later try out the blob optimization by sending a buffer.
