### ISSUE TITLE
[Question] Creating multiple read connections

### ISSUE THREAD

**Issue by mugikhan** [OP-Engineering/op-sqlite#197]
Hi,
We're using `op-sqlite` in our adapter package for `PowerSync` and have implemented a workaround to create multiple read-only connections for a SQLite database. Our database uses WAL mode, allowing multiple connections to the same database file.
To enable multiple read connections, we modify the dbFilename by prepending prefixes (`'./'.repeat(i + 1)`) to ensure each connection gets a unique key in dbMap.
Here's a smaller snippet of our implementation for context:
```
for (let i = 0; i < READ_CONNECTIONS; i++) {
  let dbName = './'.repeat(i + 1) + dbFilename;
  //We then open the database with the dbName above
  const conn = open({
    name: dbName,
    location: location
  });
  this.readConnections.push({ busy: false, connection: conn });
}
```
The full implementation can be found [here](https://github.com/powersync-ja/powersync-js/blob/35135140f239396c83f9b03e0baf0959132329f0/packages/powersync-op-sqlite/src/db/OPSqliteAdapter.ts#L88).

Given how `dbMap` currently maps connections by name, would you consider this workaround reasonable for achieving multiple read-only connections? Additionally, can we rely on the behavior of `dbMap` (using name as a key) remaining consistent in future versions, or is there a possibility this might change?

**Comment by ospfranco** [comment]
Despite this working for your use case it is definitely not safe. As stated in the documentation each operation works in their own native thread, so there is definitely the chance of data inconsistency unless you are using transactions everywhere which run serially, so no matter how many connections you open you won't get any speed benefit of multiple connections.

There are no promises regarding the internal implementation, it might change at some point depending on the requirements of the package and where paid clients might need changes. For now I have no plans on changing it.
