### ISSUE TITLE
[Bug]: Multiple commands produce op-sqlite/op_sqlite.framework/Headers/libsql.h

### ISSUE THREAD

**Issue by wogno** [OP-Engineering/op-sqlite#198]
### What happened?

After install op-sqlite/op_sqlite app is not build

"op-sqlite": {
    "sqlcipher": false,
    "crsqlite": false,
    "performanceMode": true,
    "iosSqlite": false,
    "sqliteFlags": "-DSQLITE_DQS=0",
    "fts5": false,
    "rtree": false,
    "libsql": false,
    "sqliteVec": false
  },

### op-sqlite version

11.2.3

### React Native version

0.76.3

### Reproducible Example

Just install op-sqlite/op_sqlite

**Comment by ospfranco** [comment]
I assumed you read the docs, there it is stated why this is happening.

**Comment by wogno** [comment]
@ospfranco Sorry I closed it, I found solution.

**Comment by wogno** [comment]
@virajpsimformsolutions Just look on documentation
https://ospfranco.notion.site/Installation-93044890aa3d4d14b6c525ba4ba8686f

Look this side 🚨🚨🚨 IOS PODS USE_FRAMEWORKS BREAKS OP-SQLITE 🚨🚨🚨

**Comment by jyling** [comment]
it seems that notion link is no longer accessible, anyone that encountered this like me, you can find the new documentation here

https://op-engineering.github.io/op-sqlite/docs/installation#use_frameworks
