### ISSUE TITLE
[Request]: Loading an existing database

### ISSUE THREAD

**Issue by ersyhsyn** [OP-Engineering/op-sqlite#201]
### What do you need?
```
const openAssetsDb = async () => {
    const moved = await moveAssetsDatabase({ filename: "chinook.db" });
    console.log(moved);
    if (!moved) {
      throw new Error("Could not move assets database");
    }

    try {
      const db = open({ name: "chinook.db" });

      let result = await db.executeRaw("SELECT * FROM albums");
      console.warn(result);
    } catch (e) {
      console.error("Something went wrong executing SQL commands:", e.message);
    }
  };

```
```
(NOBRIDGE) LOG  true
 (NOBRIDGE) ERROR  Something went wrong executing SQL commands: [op-sqlite] SQL statement error:1 description:no such table: albums
```

chinook.db from
https://www.sqlitetutorial.net/sqlite-sample-database/

I put the existing database under the assets folder according to the instructions on your site and linked it with npx react-native-asset@latest. When I run the sample code above, it says there is no table named albums. I wonder if it does not move the content while moving the db, I couldn't figure it out.

**Comment by ospfranco** [comment]
Create a reproducible example but I don't think there is an issue with the library but rather with your set up

**Comment by ersyhsyn** [comment]
yes, console.warn(moved) result   true

**Comment by ospfranco** [comment]
Did you already create the database before moving it? If the database already exists it is not overwritten. You can try adding overwrite to the move call:

![CleanShot 2024-12-12 at 10 35 15@2x](https://github.com/user-attachments/assets/31ee159b-689d-4d41-bbd7-445fc57fd17a)

The docs are quite clear

**Comment by ersyhsyn** [comment]
overwrite: true. solved my problem, thanks for your help.
