### ISSUE TITLE
[Request]: BigInt

### ISSUE THREAD

**Issue by steida** [OP-Engineering/op-sqlite#209]
### What do you need?

Hi. Thank you for your work. Do you plan to support BigInt?

**Comment by ospfranco** [comment]
PRs are welcome or would do it for a bit of sponsoring money. Need to figure out how Bigint is implemented and how can it be passed to the C++ side.

**Comment by steida** [comment]
expo-sqlite does not support it too, but it looks like `react-native-nitro-sqlite` supports it (at least, they have it in types)

**Comment by ospfranco** [comment]
sure, should be possible

**Comment by ospfranco** [comment]
Maybe @rflopezm you want to tackle this if you have time over the holidays?

**Comment by ospfranco** [comment]
Took a brief look, bigint support would mean just calling '.toString()' to support serialization to the types sqlite support. Returning data would be returning a string as well as there is no matching type on sqlite. So basically you will have to implement your own code to convert from string back to bigint anyways. Going to close this as trying to automate this is impossible without making it confusing for people when they inevitably start asking why are they not getting back a bigint from their queries.

**Comment by ospfranco** [comment]
![CleanShot 2024-12-21 at 15 58 05@2x](https://github.com/user-attachments/assets/3a00d10a-13fe-4cba-8a5d-d94a51fe4e0d)

Added a section to the docs for future reference
