### ISSUE TITLE
[Request]: Documentation about expo-updates conflicts

### ISSUE THREAD

**Issue by Caligone** [OP-Engineering/op-sqlite#213]
### What do you need?

It appears the Expo team has [introduced a flag](https://github.com/expo/expo/blob/540b8d8f41fed651dba4f157be4d418a7e11d058/packages/expo-updates/ios/EXUpdates.podspec#L35) that resolves conflicts with op-sqlite:
https://github.com/expo/expo/pull/30826

Adding `"expo.updates.useThirdPartySQLitePod": "true"` to `ios/Podfile.properties.json` fixes the duplicate symbols and header definition issues when `expo-updates` is the only conflicting package.

An expo plugin could also be used:
```typescript
import type { ConfigPlugin } from "@expo/config-plugins";
import { withPodfileProperties } from "@expo/config-plugins";

const withUseThirdPartySQLitePod: ConfigPlugin<never> = (expoConfig) => {
    return withPodfileProperties(expoConfig, (config) => {
        config.modResults ={
            ...config.modResults,
            "expo.updates.useThirdPartySQLitePod": "true",
        };
        return config;
    });
};

export default withUseThirdPartySQLitePod;
``` 

Perhaps the documentation could be updated to reflect this:
https://ospfranco.notion.site/Gotchas-bedf4f3e9dc1444480fc687d8917751a

**Comment by ospfranco** [comment]
Does it really solve it? AFAIK, by using `useThirdPartySQLitePod` they use the sqlite cocoapod which also compiles sqlite from source just using a cocoapod, while op-sqlite compiles it directly from sources. Did you try this?

**Comment by ospfranco** [comment]
Ah! if they skip the dependency then the behavior changed since last I saw it. Great! Thanks I will update the docs.

**Comment by ospfranco** [comment]
Done, docs have been updated. Thanks a lot!
