### ISSUE TITLE
[Request]: Upgrade sqlitevec.xcframework

### ISSUE THREAD

**Issue by jhen0409** [OP-Engineering/op-sqlite#215]
### What do you need?

It seems like the sqlite-vec binding is not the [latest version](https://github.com/asg017/sqlite-vec/releases/tag/v0.1.6), can you upgrade that? Thanks!

Or, if you like to have a build script in repo, I'd be happy to try to contribute.

**Comment by ospfranco** [comment]
please send a PR if you need such an update. Don't have a lot of time to update it myself.
