### ISSUE TITLE
[QUESTION] Using an existing expo-sqlite database

### ISSUE THREAD

**Issue by robsonbbs** [OP-Engineering/op-sqlite#217]
First of all: Thanks for the amazing lib and all the effort put on it!

I am coming from expo-sqlite, and have managed to use my old database on Android doing this:

```
const oldDBLocation = Platform.OS === 'ios' ? `${FileSystem.documentDirectory}SQLite` : '/data/data/io.app.package/files/SQLite'

// Expo implementation
export const db = SQLite.openDatabase('MAIN_DB')

// OP SQLite implementation
export const db2 = open({ name: 'MAIN_DB', location: oldDBLocation })
```

But that approach doesn't seems to work for iOS. Do you have any insight about why that doesn't work on iOS?

Running this on iOS, I can see that MAIN_DB exists on iOS path:

```
const directoryPath = FileSystem.documentDirectory
const result = await FileSystem.readDirectoryAsync(`${directoryPath}SQLite`)
console.log(JSON.stringify(result)) // Result: ["LOGS_DB","MAIN_DB"]
```

**Comment by ospfranco** [comment]
Thank you for the kind words. Interesting, it should work. What's the value of `FileSystem.documentDirectory`?

**Comment by ospfranco** [comment]
Ah, you might be missing a final `/` in the path:

```
const oldDBLocation = Platform.OS === 'ios' ? `${FileSystem.documentDirectory}SQLite/` : '/data/data/io.app.package/files/SQLite'
```

Path is just concatenated, not resolved. Read the docs carefully.

**Comment by ospfranco** [comment]
I just created a release that will try to resolve a path to prevent errors with duplicated backslashes but I don't think it is the issue here:

https://github.com/OP-Engineering/op-sqlite/releases/tag/11.2.10

**Comment by robsonbbs** [comment]
Found the issue!

I was using the file schema `file:///var/mobile/Containers/Data/Application/B4FF6A3A-5982-44E7-BEB2-F88E0DB985ED/Documents/SQLite` instead of the absolute path `/var/mobile/Containers/Data/Application/B4FF6A3A-5982-44E7-BEB2-F88E0DB985ED/Documents/SQLite/`

Thanks!
