### ISSUE TITLE
ArrayBuffer is unavailable while using react-native-macos

### ISSUE THREAD

**Issue by gokul1099** [OP-Engineering/op-sqlite#25]
I created a macos app using react-native-macos init and installed op-sqlite. When trying to run this project it is showing node_modules/@op-engineering/op-sqlite/cpp/utils.cpp:14:17 'get<bool, std::nullptr_t, bool, int, double, long, long long, std::string, ArrayBuffer>' is unavailable: introduced in macOS 10.13. I tried changing the deployment target, But that does not work.
Any workaround for this??

**Comment by ospfranco** [comment]
ArrayBuffer is a custom struct, it probably means the std::variant.get method. 10.13 is sierra, which is somewhat old, which target did you try to change it to? did you try ventura or sonoma?

**Comment by ospfranco** [comment]
In any case, if you can create a reproducible repo I will take a look

**Comment by gokul1099** [comment]
I tried setting deployment targets to 13 and 14 still the same issue. I have created a reproducible repo
https://github.com/gokul1099/op-sqlite-repro please check.

**Comment by ospfranco** [comment]
I think you changed your application target deployment target and not the library, you need to change it on the podspec/Xcode under the `op-sqlite` target. In any case, there is a new version `2.0.3` it's fixed.
