### ISSUE TITLE
SQLite code: 21 execution error: not an error

### ISSUE THREAD

**Issue by XantreGodlike** [OP-Engineering/op-sqlite#26]
```sql
CREATE TABLE segments ("distance" REAL NOT NULL, "endDate" INTEGER NOT NULL, "id" TEXT PRIMARY KEY, "index" INTEGER NOT NULL, "region" TEXT NOT NULL, "speed" REAL NOT NULL, "startDate" INTEGER NOT NULL, "tripId" TEXT NOT NULL, "startLat" REAL NOT NULL, "startLng" REAL NOT NULL, "endLat" REAL NOT NULL, "endLng" REAL NOT NULL) STRICT;
```
```
Error: [op-sqlite] SQLite code: 21 execution error: not an error
    at execute (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=dev.world.oone.driverapp&modulesOnly=false&runModule=true:422897:26)
    at execute (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=dev.world.oone.driverapp&modulesOnly=false&runModule=true:423039:32)
    at createSegmentsTable (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=dev.world.oone.driverapp&modulesOnly=false&runModule=true:422692:19)
```

fails to execute table creation
![image](https://github.com/OP-Engineering/op-sqlite/assets/57757211/9807e845-01e7-40b4-ab03-f45c19b6a095)

**Comment by ospfranco** [comment]
I just tried it and everything seems to be working for me:

![Uploading Oscar Franco Screen 000490.png…]()

Here is the code I used:

```ts
    const testDB = open({
      name: 'testDB',
    });

    testDB.execute('DROP TABLE IF EXISTS segments;');

    testDB.execute(`CREATE TABLE segments ("distance" REAL NOT NULL, "endDate" INTEGER NOT NULL, "id" TEXT PRIMARY KEY, "index" INTEGER NOT NULL, "region" TEXT NOT NULL, "speed" REAL NOT NULL, "startDate" INTEGER NOT NULL, "tripId" TEXT NOT NULL, "startLat" REAL NOT NULL, "startLng" REAL NOT NULL, "endLat" REAL NOT NULL, "endLng" REAL NOT NULL) STRICT;`,
    );

    const result = testDB.execute(`SELECT EXISTS (
      SELECT 1
      FROM sqlite_master
      WHERE type='table' 
      AND name='segments'
   );`);
```

None of the statements threw an error for me

**Comment by XantreGodlike** [comment]
I am testing on Android. Will try to experiment with clear project

**Comment by ospfranco** [comment]
Android is also working, make sure you are running the latest version


![Oscar Franco Screen 000491](https://github.com/OP-Engineering/op-sqlite/assets/1634213/35baf706-eadd-4f58-9831-0944705ecb51)

**Comment by XantreGodlike** [comment]
I figure it out - it's trimming issue, but error is confusing.
```ts
const sqlite = open({
  name: 'beb',
});
const sql = `SELECT EXISTS (
  SELECT 1
  FROM sqlite_master
  WHERE type='table' 
  AND name='your_table_name'
);
`;
const sqlTrimmed = sql.trim();

console.log('execute trimmed', sqlTrimmed, sqlite.execute(sqlTrimmed));
try {
  console.log('execute stripping sql', sql, sqlite.execute(sql));
} catch (err) {
  console.log('execute stripping sql error', err);
}
```

**Comment by ospfranco** [comment]
You are right, didn't knew SQLite would behave like this, you can see it's trying to execute "\n ". I would expect it to throw an error at the moment of preparing the statement though... weird...

![Oscar Franco Screen 000492](https://github.com/OP-Engineering/op-sqlite/assets/1634213/0bde91c6-92a9-4465-a3f6-8fd1be694fea)

**Comment by ospfranco** [comment]
Ok, looks like if the statement is parsed as empty it doesn't fail with an error code, but rather the statement pointer is returned as null, therefore meaning there is nothing to execute.

I've fixed it by just skipping the execution block if the statement is returned as NULL. Will be there in version 2.0.5

![Oscar Franco Screen 000493](https://github.com/OP-Engineering/op-sqlite/assets/1634213/f972a702-d235-4c1a-9d41-e44a144b7238)
