### ISSUE TITLE
Null value return 0 Instead Null

### ISSUE THREAD

**Issue by shiroze** [OP-Engineering/op-sqlite#29]
DB Table Value
![image](https://github.com/OP-Engineering/op-sqlite/assets/6022114/24f0d7cd-cfa7-4a7d-a679-6e189227d75f)

Select Query Result
![image](https://github.com/OP-Engineering/op-sqlite/assets/6022114/8bcbe888-3390-4374-aa09-d466d8983399)

Did this bug ? `Null` will replaced into `0` ?
If I want to get `null` value instead `0` ?

Packages :
```
"@op-engineering/op-sqlcipher": "^1.0.15",
"react": "18.2.0",
"react-native": "0.72.6",
```

**Comment by ospfranco** [comment]
Looks correct to me. You should try to create a minimal reproducible example

![Oscar Franco Screen 000519](https://github.com/OP-Engineering/op-sqlite/assets/1634213/c822e3f7-8ff2-4cd8-8cd8-7686e28c2ba3)

**Comment by shiroze** [comment]
Still giving me the same result. newest release package give me error `openssl-config.cmake`
![image](https://github.com/OP-Engineering/op-sqlite/assets/6022114/d60308bc-a784-442b-8e3e-b3253afc2a97)

**Comment by ospfranco** [comment]
If you are having an issue with sqlcipher, create an issue in the repo. Also, create a reproducible example, I already tried to reproduce it and found no issues, don't have time to create a project from scratch and find the cause.

**Comment by EduFrazao** [comment]
Hi @shiroze.
I got this error too, with async methods, on android.
I've send a PR and i'm waiting for review now. If it gets accepted, could you check your use case again?

**Comment by scalhoun** [comment]
> Hi @shiroze. I got this error too, with async methods, on android. I've sent a PR and i'm waiting for review now. If it gets accepted, could you check your use case again?

I ran into the same issue without using op-sqlcipher.  I ended up just reverting back to the old repo for now.  I can test the PR as well.

**Comment by EduFrazao** [comment]
> > Hi @shiroze. I got this error too, with async methods, on android. I've sent a PR and i'm waiting for review now. If it gets accepted, could you check your use case again?
> 
> I ran into the same issue without using op-sqlcipher. I ended up just reverting back to the old repo for now. I can test the PR as well.

Nice, this is the PR:
https://github.com/OP-Engineering/op-sqlite/pull/48

The null fix is among others small fixes.

**Comment by ospfranco** [comment]
Sorry, I've been traveling the last days. Will take a look soon

**Comment by EduFrazao** [comment]
Hi @shiroze!
Did you had the time to test this problem with the 2.0.18 release?

**Comment by shiroze** [comment]
> Hi @shiroze! Did you had the time to test this problem with the 2.0.18 release?

Sorry for late reply and yes, already tested and it give me the result I want.

thank you
