### ISSUE TITLE
[2.0.15]  iOS throws use of undeclared identifier sqlite3_enable_load_extension / sqlite3_load_extension

### ISSUE THREAD

**Issue by efstathiosntonas** [OP-Engineering/op-sqlite#42]
**Describe the bug**
After upgrading to `2.0.15` I get these errors: 

 `use of undeclared identifier sqlite3_enable_load_extension` and `use of undeclared identifier sqlite3_load_extension` on iOS.

It seems that culprit is the `use_frameworks! :linkage => :static` on `Podfile`. I need static linkage for `react-native-firebase`. This is the PR that started causing the issue: https://github.com/OP-Engineering/op-sqlite/pull/40

**Versions:**
 - OS and version: iOS 17.2, Xcode 15.2
 - op-sqlite version: 2.0.15
 - RN version: 0.73.2 using expo-modules-core on expo@50

**Reproducible example**
 https://github.com/efstathiosntonas/bare-react-native-expo-svg-transformer-issue , I had created it a while ago for a bug on react-native-svg-transformer so just ignore that.

**Comment by ospfranco** [comment]
Just released 2.0.16. It seems to work for me. Can you give it a try?

**Comment by efstathiosntonas** [comment]
Unfortunately not. Did all the necessary cleaning but still get it, tried on both my project and repro repo.

**Comment by ospfranco** [comment]
can you remove the pods folder and do a clean pod install?

**Comment by efstathiosntonas** [comment]
already did that with `pod deintegrate`, this is the cleaning process I used: 

1. delete yarn.lock and node_modules
2. `pod deintegrate`
3. delete Derived Data, clean build folder
4. install packages again
5. `pod install`

**Comment by efstathiosntonas** [comment]
Thanks @ospfranco and thank you for your patience in this one, static linkage it a pita 😓

**Comment by ospfranco** [comment]
https://github.com/mapnik/mapnik-support/issues/119

Ah, this suggest it might be trying to use the embedded sqlite version instead of the compiled sources... that's wild. let me try something.

**Comment by efstathiosntonas** [comment]
great finding! I use Sonoma 14.2.1 if that make sense in any way.

**Comment by ospfranco** [comment]
Ah look at that, if I change the import to search for user paths first I get symbol redefinitions. I guess some other framework is also using sqlite3 and it clashes because everything will be linked a single namespace...

Not really sure how to solve this though

![Oscar Franco Screen 000861](https://github.com/OP-Engineering/op-sqlite/assets/1634213/120b64ad-4b9c-4c35-a866-4e036189cb66)

**Comment by ospfranco** [comment]
Add this to your Podfile and give it a try:

```ruby
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('op-sqlite')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end
```

**Comment by ospfranco** [comment]
shame there is no easier solution but yeah, I will add it later
