### ISSUE TITLE
Doubt: quick-sqlite compatibility

### ISSUE THREAD

**Issue by EduFrazao** [OP-Engineering/op-sqlite#46]
Hi @ospfranco. Long time no see you! Glad to see that you are back :).
I've read the API, and seems to be a drop-in replacement to quick-sqlite. I'm right?
Did you check the new JSONB format from SQLite 3.45.0? Interested in a patch?

And the new numbers are amazing. I will read your code right now :). Thank you very mutch.

**Comment by ospfranco** [comment]
Hi Edu! :) yeah sure JSON Patch sounds good

**Comment by EduFrazao** [comment]
> Hi Edu! :) yeah sure JSON Patch sounds good

Nice! I will do that. Thanks!
