### ISSUE TITLE
Support for Web

### ISSUE THREAD

**Issue by listepo** [OP-Engineering/op-sqlite#47]
It would be nice to have support for Web

**Comment by ospfranco** [comment]
You can't. On browsers you only have indexed db which is key value. Another package could provide a unified API but it's not possible to have sqlite running in the browser

**Comment by listepo** [comment]
but what about https://github.com/sql-js/sql.js?

**Comment by ospfranco** [comment]
Have you read the readme. That's not real SQLite.
