### ISSUE TITLE
Throw no error when execute complicated sql query

### ISSUE THREAD

**Issue by linhttbk97** [OP-Engineering/op-sqlite#5]
I have query that create and insert data like [this](https://justpaste.it/8yo94) 
When I called db.executeAsync(query) -> I got an error :  [Error: [op-sqlite] SQL execution error: not an error] 
I don't know it actually is but all tables and data were created successfully

**Comment by ospfranco** [comment]
There is an error somewhere on your query. This is what the debugger is showing:

![Oscar Franco Screen 000361](https://github.com/OP-Engineering/op-sqlite/assets/1634213/18539e22-8c4d-4525-8d25-4728064dc795)

The returned code is SQLITE_MISSUSE = 21, meaning you are doing something wrong. The query that is throwing the error is the first insertion, but I don't know which one of the insertions is failing.

![Oscar Franco Screen 000362](https://github.com/OP-Engineering/op-sqlite/assets/1634213/57350ef6-2f6b-4b40-b61d-a424f3a05440)

I don't think it is a problem with the library but with your SQL query

**Comment by linhttbk97** [comment]
But I just pasted it on Database Browser For Sqlite and run that query. It worked normally @ospfranco btw many thanks

**Comment by ospfranco** [comment]
I released a new version that also prints the error code, so you can debug for yourself. Try running the commands one by one and see what is happening, but as stated I don't think the library is doing anything wrong, but rather a SQL syntax error.

**Comment by linhttbk97** [comment]
Yeah, I'm using sqlite 3.42. I could be string escaped problem. Thanks
