### ISSUE TITLE
TypeORM Support

### ISSUE THREAD

**Issue by L-U-C-K-Y** [OP-Engineering/op-sqlite#6]
Hi @ospfranco 

Many thanks for this new library, it looks very interesting. 

I am using react-native-quick-sqlite with TypeORM which makes the DX a lot better. 

Can I use their docs, patch, and the mentioned TypeORM driver too, or is that not ready yet?

Thanks

**Comment by ospfranco** [comment]
No, I removed TypeORM support, it was too much of a hassle keeping up with their changes, and breaking changes and their release process is super slow. 

I would suggest you create a new package and implement the driver there. [It's just a single JS function](https://github.com/ospfranco/react-native-quick-sqlite/blob/main/src/index.ts#L348).
