### ISSUE TITLE
Question: Load 300k Records from DB

### ISSUE THREAD

**Issue by mugikhan** [OP-Engineering/op-sqlite#75]
I have a question regarding the screenshot and results posted on the README. I've gone ahead and run the example project on my iPhone 15 Pro (physical device) and could not reproduce similar results. The table below describes the results when running the example application.

Test | Test 1 | Test 2 | Test 3 | Average time (ms)
-- | -- | -- | -- | --
Query 300k Records (Normal Query) | 5860 | 6054 | 5592 | 5835
Query 300k Records (Raw Query) | 6285 | 6299 | 5917 | 6167
Query 300k Records (Normal Query, performance mode) | 5667 | 5557 | 6101 | 5775
Query 300k Records (Raw Query, performance mode) | 5985 | 5885 | 6394 | 6088

I also created a sample project using Expo (react-native) and tested the same scenario vs react-native-quick-sqlite (v8.0.6). This was with the performance mode flag `OP_SQLITE_PERF=1` enabled for op-sqlite. The results below are significantly different to the results shown in the README.

Test | op-sqlite (average in ms) | rnq-sqlite (average in ms)
-- | -- | --
Query 300k Records | 5777.26 | 7398.74

Could you please let me know what would cause the big difference in results? 
I can provide more details about my environment and setup if needed.

**Versions:**

- OS and version: iOS 17.4
- op-sqlite version: 2.0.20
- RN version: 0.73.4
- New Architecture: Yes

**Reproducible example**
Followed the setup and tests in the example project.
https://github.com/OP-Engineering/op-sqlite/blob/main/example/src/Database.ts

**Comment by ospfranco** [comment]
interesting, did you compile in release mode or in debug mode?

**Comment by mugikhan** [comment]
> interesting, did you compile in release mode or in debug mode?

These were run in debug mode for both projects. Both projects ran the tests 3 times for average values.

**Comment by ospfranco** [comment]
Run them in release mode, makes a big difference

**Comment by ospfranco** [comment]
Tested this again just to be sure I'm not crazy

![image](https://github.com/OP-Engineering/op-sqlite/assets/1634213/2677bd6d-3b34-4aea-927b-e3d2ba2ca6e3)

Closing this

**Comment by mugikhan** [comment]
Hi, just reopening this for some more insight. I've now tested it in release mode on two Android devices and was wondering what could be causing it to be much slower than iOS. Both tests were run in performance mode.

Test | Samsung S22 | Pixel 6 | iPhone 15 pro
-- | -- | -- | -- | --
Query 300k Records (Normal Query) | 918ms | 1126ms | 420ms
Test 1 (1000 Inserts not in a transaction) | 12595ms | 7942ms | 565ms

This is what the code looks like for Test 1:
```ts
for (let i = 0; i < 1000; i++) {
  const n = randomIntFromInterval(0, 100000);
  await this.dbAdapter.execute("INSERT INTO t1(a, b, c) VALUES(?, ?, ?)", [
      i + 1,
      n,
      numberName(n),
   ]);
}
```

**Comment by ospfranco** [comment]
Like I said, compile in release mode:

![CleanShot 2024-05-17 at 11 11 33@2x](https://github.com/OP-Engineering/op-sqlite/assets/1634213/7d53d817-522e-43f0-a42c-848de4c2f3c0)

Going to lock this.
