### ISSUE TITLE
How to Load of native extensions 

### ISSUE THREAD

**Issue by Volland** [OP-Engineering/op-sqlite#78]
Thank you for your work.  I do not see a option to ask question or any other forum so i decide to create and issue. 
Could you guide me in one challenge. How to compile and load native extension to op-sql ? 
I keen to use cr-sql https://github.com/vlcn-io/cr-sqlite  and vss  https://github.com/asg017/sqlite-vss  extensions 
So it is a 3 different extension that should be loaded. 
I havent figure out how to compile and select a proper binaries on react native 
Thanks in advance for your answer

**Comment by ospfranco** [comment]
Extensions need to be compiled individually with their own instructions compilers but targeting the required mobile target (iOS x86_64 sim, iOS aarch64 sim, iOS aarch64, Android x86_64, Android armv7, etc.), there is no one size fit all on how to compile each extension. Once you have that you need to produce .so libraries that can be loaded on runtime and package them in your app bundle. Once you have that there is an available API call to load them, check the docs for that.

I haven't tried loading an extension myself, people asked to expose the binding so I did but it's too much work for me to do without sponsoring.

**Comment by Volland** [comment]
@ospfranco i get cr-sql extension compiled but when i try to load it i got an error 
[Error: Exception in HostFunction: dlopen(file:///Users/volodymyrpavlyshyn/Library/Developer/CoreSimulator/Devices/879E995D-9AF9-4DED-B238-723FB6D5B05D/data/Containers/Data/Application/3F009256-4FD4-4D58-AE1C-0DA3CAD8E45A/Documents/bins/crsqlite.bin.dylib, 0x000A): tried: '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRootfile:///Users/volodymyrpavlyshyn/Library/Developer/CoreSimulator/Devices/879E995D-9AF9-4DED-B238-723FB6D5B05D/data/]

**Comment by ospfranco** [comment]
Sorry buddy, no idea. The stack doesn't give me any info. Could be that the dylib is not where you expect

**Comment by Volland** [comment]
```
    const pathToFile = './assets/bin/cr-sql/crsqlite-ios.xcframework/ios-arm64_x86_64-simulator/crsqlite.framework/crsqlite.bin'
    const asset = await Asset.fromModule(require(pathToFile)).downloadAsync();
    const extName = pathToFile.split('/').pop()
    // const asset = await Asset.fromModule(require(pathToFile)).downloadAsync();
     const path = FileSystem.documentDirectory + `bins/${extName}`
     console.log({ path })
     await FileSystem.copyAsync({
       from: asset.localUri,
       to: path,
     });
     console.log('load extension')
     db1.loadExtension(path, 'sqlite3_crsqlite_init')
```
i see that i have lib copied and i could rich this file

**Comment by Volland** [comment]
@ospfranco after a small investigation 
- it dont like "file://" prefix
- it is add .dylib and .so extension to a path even if extension are there 
after i twick a bit a path i get it running on android

**Comment by ospfranco** [comment]
- "file://" is a URI, so yeah, that won't work, you need raw paths to the file system.
- I think dylib is iOS and .so is android, but basically they are dynamic libraries, but I don't understand what you mean with "extension are there"?

**Comment by Volland** [comment]
so i have a path in a file system like file//aa/bb/crsql.so op-sql try to load file//aa/bb/crsql.so.so 
we what I made - I removed file:// prefix and removing a extension from file name and it is working
