### ISSUE TITLE
Bundle some extensions in the package

### ISSUE THREAD

**Issue by ospfranco** [OP-Engineering/op-sqlite#79]
Compiling, packaging and loading extensions is complex and error prone. It would be nice if we could take care of this for the most common and used libraries so people only need to turn on a flag an everything is taken care for them.

I've already started with `cr-sqlite`, you would only need to add `OP_SQLITE_CRSQLITE=1` to your env.

 I however need more time/effort since every extension has different compilation steps and targets.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/OP-Engineering) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/OP-Engineering/op-sqlite/issues/79">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/79/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/79/pledge.svg">
</picture>
</a>

**Comment by ospfranco** [comment]
cr-sqlite has been merged, as well as fts5. Other extensions might be requested but will require sponsoring (at least from my part) or PRs.

**Comment by seanstrom** [comment]
@ospfranco Do you happen to know if any ULID extensions for sqlite would be compatible with op-sqlite?

**Comment by ospfranco** [comment]
I'm not familiar with the sqlite universe of plugins/extensions, but anything that runs on sqlite itself is compatible with op-sqlite (albeit it might require some minor tweaks to the JS → c++ mapping).

**Comment by ospfranco** [comment]
I've packaged all the extensions I wanted into the lib. For now closing this. Open a new issue if a new one is necessary.
