### ISSUE TITLE
I gets back sqlite version 3.42.0 for ios

### ISSUE THREAD

**Issue by Volland** [OP-Engineering/op-sqlite#82]
**Describe the bug**
I getting back sqlite version 3.42 that do not support jsonb function 

**Versions:**

- OS and version: iOS 17
- op-sqlite version: 5.0.1 
- RN version:  0.73.6
- New Architecture: Yes

**Reproducible example**
I just open a new db and call 
```
import {open} from '@op-engineering/op-sqlite'
    const dbname = `${ generateUUID()}-testdb.sqlite`

    const db = open({name: dbname})
    const version =  db.execute('select sqlite_version();')
    console.log('db name', dbname, 'version  ', version.rows)
```
on android symulator i see a correct version but on ios one i see :
sqlite version   {"_array": [{"sqlite_version()": "3.42.0"}], "item": [Function anonymous], "length": 1}
 LOG  {"isSimulator": true, "os": "ios"}
 ERROR  [Error: Exception in HostFunction: [op-sqlite] SQL prepare statement error: no such function: jsonb]

**Comment by Volland** [comment]
I also get old version on device

**Comment by ospfranco** [comment]
Can you update to the latest version and make sure the iOS flag is not turned on.

Check the news docs on the install page on how to configure the package now

**Comment by Volland** [comment]
Nop I using regular one . I just install it from npm . I didn't see any extra flags in a doc . Where I could find install guide ?

**Comment by ospfranco** [comment]
Here are the docs for the latest version

https://ospfranco.notion.site/Installation-93044890aa3d4d14b6c525ba4ba8686f

Configuration section

**Comment by Volland** [comment]
so i switched to lates and use 
```
"op-sqlite": {
    "sqlcipher": false,
    "crsqlite": true,
    "performanceMode": "1",
    "iosSqlite": false
  },
```
I still get old version 
db name 4129c483-f2be-42ca-9919-ae43ae58c2f0-testdb.sqlite version   {"_array": [{"sqlite_version()": "3.42.0"}], "item": [Function anonymous], "length": 1}

**Comment by Volland** [comment]
Yea . I tried to doit after expo pre build and before also . I tried few combinations

**Comment by ospfranco** [comment]
iOS or Android?

In any case. As stated on the bug description ticket. You need to create a reproducible example. I don't like working for free. For me in the example app it is working, so it has to be something about your project setup.

**Comment by Volland** [comment]
I could put it on git hub as open repo , I just follow a docs and unfortunately it give me old version all the time . I ll test with other teammates and include a link to a repo in a ticket .

**Comment by ospfranco** [comment]
There is one more possibility. If you are using static linking that breaks the compilation and forces iOS to use the phone embedded version. You can read through the docs to exclude op-sqlite from static linking, there is a snippet there somewhere.

**Comment by ospfranco** [comment]
Closing this as it has no reproducible example. Feel free to comment if you find the issue or send a reproducible example and I will re-open it.
