### ISSUE TITLE
Binary data example is not working as expected 

### ISSUE THREAD

**Issue by Volland** [OP-Engineering/op-sqlite#83]
**Describe the bug**
I try to store a binary data to a table 
As recomended i use 

```
        let binaryData = new Uint8Array(2);
        binaryData[0] = 42;
    db.execute(
      `create table if not exists nodes (
        id varchar(36) primary key not null,
        label varchar,
        vectorLabel blob
      );`
    );
        const insert1 =  db.prepareStatement(
          'INSERT INTO nodes (id, label, vectorLabel) VALUES (?, ?, ?);'
        );
  insert1.bind([generateUUID(),'tea',binaryData])
```
I get error : [Error: Exception in HostFunction: Unknown JSI ArrayBuffer to variant value conversion, received object instead of ArrayBuffer]

I pass a ArrayBuffer as a parameter insead on Uint8Array and it solve issue but it is not align with a docs etc 

**Versions:**

OS and version: iOS 17
op-sqlite version: 4.0.0-beta1
RN version: 0.73.6
New Architecture: Yes

**Reproducible example**
Create a minimal reproduction example, otherwise I won't take a look. I'm serious, no example = no solution.

**Comment by ospfranco** [comment]
ah. The examples mention the execute functions, not the prepared statements. You need to use:

```
insert1.bind([generateUUID(), 'tea', binaryData.buffer])
```

There is some convenience conversion on the other methods that is not present on the `bind` function

**Comment by ospfranco** [comment]
I added the same convenience conversion and also fixed a memory leak. It will be released on next version.
