### ISSUE TITLE
Increase the limit of attached databases

### ISSUE THREAD

**Issue by jel-atolcd** [OP-Engineering/op-sqlite#84]
Hello

The doc says:

> SQLite has a limit for attached databases: A default of 10, and a global max of 125

But I can't find a way to increase it with the library API.

Reading the SQLite doc, there is a function `sqlite3_limit(db,SQLITE_LIMIT_ATTACHED,size)`. Is there a way to call it?

Thanks

**Comment by ospfranco** [comment]
Maybe there is a compilation flag, otherwise no. There is currently no exposed function to call sqlite3_limit.

**Comment by jel-atolcd** [comment]
Seems like I misunderstood the SQLite doc. Apparently there is a compilation flag `SQLITE_MAX_ATTACHED` (default 10, max 125). Then `sqlite3_limit(db,SQLITE_LIMIT_ATTACHED,size)` can be used at runtime only to **lower** the limit set at compile time.

So the flag should do the work. I will try that and report back.

Thanks for the help!

**Comment by ospfranco** [comment]
This on the `package.json` should do the trick for you.

```json
"op-sqlite": {
  "sqliteFlags": "-DSQLITE_MAX_ATTACHED=125",
}
```

Closing this. If you have another issue, just comment and I will re-open this.

**Comment by jel-atolcd** [comment]
I confirm that it works on version 3.0.7 by adding `OPSQLiteFlags="-DSQLITE_MAX_ATTACHED=125"` in `android/gradle.properties`

5.0.5 doesn't build so I can't confirm that it works with the new way (`package.json` config).

Btw, is the old 3.0.7 doc still available?

**Comment by ospfranco** [comment]
I answered regarding your build issue on the other ticket. Regarding docs, no. You can take a look at old states in this repo to find the README but I moved everything to notion because it is too much work to keep everything in sync.
