### ISSUE TITLE
Fail to build ios for 5.0.5 lib version 

### ISSUE THREAD

**Issue by Volland** [OP-Engineering/op-sqlite#89]
**Describe the bug**
I am not able to build expo app with 5.0.5
https://github.com/Volland/op-sql-db-version-ios/tree/main

**Versions:**

- OS and version: iOS 17
- op-sqlite version: 5.0.5
- RN version:  0.73.6
- New Architecture:  Yes 

**Reproducible example**
Follow repo https://github.com/Volland/op-sql-db-version-ios/tree/main

Error : 
  error: Error Domain=NSCocoaErrorDomain Code=4 "The file “clang” doesn’t exist." UserInfo={NSFilePath=/usr/local/opt/llvm/bin/clang}

❌  error: Error Domain=NSCocoaErrorDomain Code=4 "The file “clang” doesn’t exist." UserInfo={NSFilePath=/usr/local/opt/llvm/bin/clang}

❌  error: Error Domain=NSCocoaErrorDomain Code=4 "The file “clang” doesn’t exist." UserInfo={NSFilePath=/usr/local/opt/llvm/bin/clang}

❌  error: Error Domain=NSCocoaErrorDomain Code=4 "The file “clang” doesn’t exist." UserInfo={NSFilePath=/usr/local/opt/llvm/bin/clang}

**Comment by ospfranco** [comment]
Your repo has not been prebuilt

**Comment by ospfranco** [comment]
Getting an error on your repo when trying to install the pods

![CleanShot 2024-04-23 at 09 27 56@2x](https://github.com/OP-Engineering/op-sqlite/assets/1634213/67be3e17-fb6c-42c1-809d-da28552b0101)

**Comment by ospfranco** [comment]
Seems to be compiling fine for me

![CleanShot 2024-04-23 at 09 33 09@2x](https://github.com/OP-Engineering/op-sqlite/assets/1634213/1c3f9352-e2f4-442d-b3d6-88d1ec4a0ac5)

**Comment by ospfranco** [comment]
Your repo seemed to be missing the op-sqlite dependency. But even after I added it and did a pod-install everything is compiling.

![CleanShot 2024-04-23 at 09 35 31@2x](https://github.com/OP-Engineering/op-sqlite/assets/1634213/82ac1423-944a-497a-89a7-a6ae220e3b7e)

**Comment by Volland** [comment]
@ospfranco  i found issue . I use Cozodb in a project that uses SQLite, too, and I don't know how it influences the version of SQLite that Op Library is using. it is reproducing only for ios . if you have any idea why . let me know but for regular user I it is not a issue
