### ISSUE TITLE
libcrypto.so not found

### ISSUE THREAD

**Issue by efstathiosntonas** [OP-Engineering/op-sqlite#97]
**Describe the bug**
Hi @ospfranco, something is interfering with [react-native-keys](https://github.com/numandev1/react-native-keys) library and after building on react-native@0.74 I get the following error:

```
dlopen failed: library "libcrypto.so" not found: needed by /data/app/~~lJuXe3_5lJkjj8LthPNdYA==/com.awesomeproject-QydFPfNIqGQkdQORPY-MSQ==/base.apk!/lib/arm64-v8a/libreact-native-keys.so in namespace clns-6
```

op-sqlite settings: 

```json
  "op-sqlite": {
    "sqlcipher": false,
    "crsqlite": false,
    "performanceMode": "2",
    "iosSqlite": false
  }
```

The moment I remove `op-slite` everything is back to normal, by removing `react-native-keys` and keeping only `op-sqlite` everything is back to normal too. Weird things 😅 

Do you have any ideas what is happening? I believe at some point it strips out `libcrypto` no matter if `sqlcipher` is true or false.

Please note that in `react-native@0.73.x` everything is working fine, it only happens on 0.74.

**Versions:**

- OS and version: Android 14
- op-sqlite version: 6.0.1
- RN version: 0.74.0
- New Architecture: No

**Reproducible example**
Please build using Android Studio, not cli. 

https://github.com/efstathiosntonas/0_74-react-native-keys-op-sqlit

**Comment by ospfranco** [comment]
Is that thing really secure? It has a hardcoded password in the source code.

https://github.com/numandev1/react-native-keys/blob/main/cpp/crypto.cpp

But no idea, they shouldn't interfere with each other.

**Comment by efstathiosntonas** [comment]
Nothing is secure of course 😄 

Been trying for 2 days to find why this is happening...

**Comment by ospfranco** [comment]
That's not true. You can actually secure it, it's just a lot of work. It involves https://support.apple.com/guide/deployment/managed-device-attestation-dep28afbde6a/web, not shipping secrets but actually downloading them and storing them in a secure manner, etc. I've been too lazy to write about it because it doesn't make to do it for free or per app, There are companies/frameworks that offer at a framework/service.

Back to the topic. Doubt that library works and don't know what could be wrong, op-sqlite does not strip anything, if you face a double libcrypto.so there docs says how you can solve it, but that's a different issue.

**Comment by efstathiosntonas** [comment]
cc: @numandev1

**Comment by ospfranco** [comment]
No no, please don't drag me into this discussion.

**Comment by efstathiosntonas** [comment]
@ospfranco just fyi, managed to solve it. 

I runned `./gradlew assembleDebug` from the command line and everything was fine, the app was able to run. 

This lead me to a not aligned configuration between the Android Studio and CLI `./gradlew`. 

The issue was in Preferences -> Build, Execution, Deployment -> Build Tools -> Gradle -> Gradle User Home on Android Studio, it was using this path `/Applications/Android Studio.app/Contents/jbr/Contents/Home` instead of `/Users/stathis/.gradle`. 

Android madness at it's finest.

**Comment by ospfranco** [comment]
don't know if using a global Gradle won't bring problems down the line. But glad you solved it!

**Comment by efstathiosntonas** [comment]
Agreed, there's definitely something off in my setup.
